library(medfate)

data(examplemeteo)
data(exampleforestMED)
data(SpParamsMED)
d = 100:110

test_that("Can produce all basic plots",{
  examplesoil = soil(defaultSoilParams(2))
  control = defaultControl("Granier")
  control$verbose = FALSE
  x = forest2spwbInput(exampleforestMED,examplesoil, SpParamsMED, control)
  S1<-spwb(x, examplemeteo[d,], latitude = 41.82592, elevation = 100)
  
  expect_s3_class(plot(S1, "PET_Precipitation"), "ggplot")
  expect_s3_class(plot(S1, "PET_NetRain"), "ggplot")
  expect_s3_class(plot(S1, "Snow"), "ggplot")
  expect_s3_class(plot(S1, "Export"), "ggplot")
  expect_s3_class(plot(S1, "Evapotranspiration"), "ggplot")
  expect_s3_class(plot(S1, "SoilPsi"), "ggplot")
  expect_s3_class(plot(S1, "SoilRWC"), "ggplot")
  expect_s3_class(plot(S1, "SoilTheta"), "ggplot")
  expect_s3_class(plot(S1, "SoilVol"), "ggplot")
  expect_s3_class(plot(S1, "PlantExtraction"), "ggplot")
  expect_s3_class(plot(S1, "LAI"), "ggplot")
  expect_s3_class(plot(S1, "PlantLAI"), "ggplot")
  expect_s3_class(plot(S1, "PlantStress"), "ggplot")
  expect_s3_class(plot(S1, "PlantPsi"), "ggplot")
  expect_s3_class(plot(S1, "PlantTranspiration"), "ggplot")
  expect_s3_class(plot(S1, "TranspirationPerLeaf"), "ggplot")
  expect_s3_class(plot(S1, "PlantGrossPhotosynthesis"), "ggplot")
  expect_s3_class(plot(S1, "GrossPhotosynthesisPerLeaf"), "ggplot")
})

test_that("Can produce all advanced plots",{
  examplesoil2 = soil(defaultSoilParams(4))
  control = defaultControl("Sperry")
  control$verbose = FALSE
  x2 = forest2spwbInput(exampleforestMED,examplesoil2, SpParamsMED, control)
  S2<-spwb(x2, examplemeteo[d,], latitude = 41.82592, elevation = 100)
  
  expect_s3_class(plot(S2, "HydraulicRedistribution"), "ggplot")
  expect_s3_class(plot(S2, "SoilPlantConductance"), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiMin"), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiMax"), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiRange"), "ggplot")
  expect_s3_class(plot(S2, "StemPsi"), "ggplot")
  expect_s3_class(plot(S2, "RootPsi"), "ggplot")
  expect_s3_class(plot(S2, "PlantNetPhotosynthesis"), "ggplot")
  expect_s3_class(plot(S2, "NetPhotosynthesisPerLeaf"), "ggplot")
  expect_s3_class(plot(S2, "PlantWUE"), "ggplot")
  expect_s3_class(plot(S2, "PlantAbsorbedSWR"), "ggplot")
  expect_s3_class(plot(S2, "AbsorbedSWRPerLeaf"), "ggplot")
  expect_s3_class(plot(S2, "PlantNetLWR"), "ggplot")
  expect_s3_class(plot(S2, "NetLWRPerLeaf"), "ggplot")
  expect_s3_class(plot(S2, "AirTemperature"), "ggplot")
  expect_s3_class(plot(S2, "CanopyTemperature"), "ggplot")
  expect_s3_class(plot(S2, "SoilTemperature"), "ggplot")
  expect_s3_class(plot(S2, "CanopyEnergyBalance"), "ggplot")
  expect_s3_class(plot(S2, "SoilEnergyBalance"), "ggplot")
})
