library(medfate)

data(examplemeteo)
data(exampleforestMED)
data(SpParamsMED)
d = 100:110

test_that("Can produce all basic spwb plots",{
  examplesoil = soil(defaultSoilParams(2))
  control = defaultControl("Granier")
  control$verbose = FALSE
  x = forest2spwbInput(exampleforestMED,examplesoil, SpParamsMED, control)
  S1<-spwb(x, examplemeteo[d,], latitude = 41.82592, elevation = 100)
  
  expect_s3_class(plot(S1, "PET_Precipitation"), "ggplot")
  expect_s3_class(plot(S1, "PET_NetRain"), "ggplot")
  expect_s3_class(plot(S1, "Snow"), "ggplot")
  expect_s3_class(plot(S1, "Export"), "ggplot")
  expect_s3_class(plot(S1, "WTD"), "ggplot")
  expect_s3_class(plot(S1, "Evapotranspiration"), "ggplot")
  expect_s3_class(plot(S1, "SoilPsi"), "ggplot")
  expect_s3_class(plot(S1, "SoilRWC"), "ggplot")
  expect_s3_class(plot(S1, "SoilTheta"), "ggplot")
  expect_s3_class(plot(S1, "SoilVol"), "ggplot")
  expect_s3_class(plot(S1, "PlantExtraction"), "ggplot")
  expect_s3_class(plot(S1, "LAI"), "ggplot")
  expect_s3_class(plot(S1, "PlantLAI"), "ggplot")
  expect_s3_class(plot(S1, "PlantStress"), "ggplot")
  expect_s3_class(plot(S1, "StemPLC"), "ggplot")
  expect_s3_class(plot(S1, "PlantPsi"), "ggplot")
  expect_s3_class(plot(S1, "PlantTranspiration"), "ggplot")
  expect_s3_class(plot(S1, "TranspirationPerLeaf"), "ggplot")
  expect_s3_class(plot(S1, "PlantGrossPhotosynthesis"), "ggplot")
  expect_s3_class(plot(S1, "GrossPhotosynthesisPerLeaf"), "ggplot")
})

test_that("Can produce all advanced spwb plots",{
  examplesoil2 = soil(defaultSoilParams(4))
  control = defaultControl("Sperry")
  control$verbose = FALSE
  x2 = forest2spwbInput(exampleforestMED,examplesoil2, SpParamsMED, control)
  S2<-spwb(x2, examplemeteo[d,], latitude = 41.82592, elevation = 100)
  
  expect_s3_class(plot(S2, "HydraulicRedistribution"), "ggplot")
  expect_s3_class(plot(S2, "SoilPlantConductance"), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiMin"), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiMax"), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiRange"), "ggplot")
  expect_s3_class(plot(S2, "StemPsi"), "ggplot")
  expect_s3_class(plot(S2, "RootPsi"), "ggplot")
  expect_s3_class(plot(S2, "TempMin_SL"), "ggplot")
  expect_s3_class(plot(S2, "TempMin_SH"), "ggplot")
  expect_s3_class(plot(S2, "TempMax_SL"), "ggplot")
  expect_s3_class(plot(S2, "TempMax_SH"), "ggplot")
  expect_s3_class(plot(S2, "GSWMin_SL"), "ggplot")
  expect_s3_class(plot(S2, "GSWMin_SH"), "ggplot")
  expect_s3_class(plot(S2, "GSWMax_SL"), "ggplot")
  expect_s3_class(plot(S2, "GSWMax_SH"), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiMin_SL"), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiMin_SH"), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiMax_SL"), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiMax_SH"), "ggplot")
  expect_s3_class(plot(S2, "StemRWC"), "ggplot")
  expect_s3_class(plot(S2, "StemSympRWC"), "ggplot")
  expect_s3_class(plot(S2, "LeafRWC"), "ggplot")
  expect_s3_class(plot(S2, "LeafSympRWC"), "ggplot")
  expect_s3_class(plot(S2, "PlantWaterBalance"), "ggplot")
  expect_s3_class(plot(S2, "PlantNetPhotosynthesis"), "ggplot")
  expect_s3_class(plot(S2, "NetPhotosynthesisPerLeaf"), "ggplot")
  expect_s3_class(plot(S2, "PlantWUE"), "ggplot")
  expect_s3_class(plot(S2, "PlantAbsorbedSWR"), "ggplot")
  expect_s3_class(plot(S2, "AbsorbedSWRPerLeaf"), "ggplot")
  expect_s3_class(plot(S2, "PlantNetLWR"), "ggplot")
  expect_s3_class(plot(S2, "NetLWRPerLeaf"), "ggplot")
  expect_s3_class(plot(S2, "Temperature"), "ggplot")
  expect_s3_class(plot(S2, "AirTemperature"), "ggplot")
  expect_s3_class(plot(S2, "CanopyTemperature"), "ggplot")
  expect_s3_class(plot(S2, "SoilTemperature"), "ggplot")
  expect_s3_class(plot(S2, "CanopyEnergyBalance"), "ggplot")
  expect_s3_class(plot(S2, "SoilEnergyBalance"), "ggplot")
})

test_that("Can produce all advanced subdaily spwb plots",{
  examplesoil2 = soil(defaultSoilParams(4))
  control = defaultControl("Sperry")
  control$verbose = FALSE
  control$subdailyResults = TRUE
  x2 = forest2spwbInput(exampleforestMED,examplesoil2, SpParamsMED, control)
  S2<-spwb(x2, examplemeteo[d,], latitude = 41.82592, elevation = 100)
  
  expect_s3_class(plot(S2, "LeafPsi", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafPsiAverage", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "RootPsi", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "StemPsi", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "StemRWC", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafRWC", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "StemSympRWC", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafSympRWC", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "PlantExtraction", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "PlantTranspiration", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafTranspiration", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "PlantGrossPhotosynthesis", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafGrossPhotosynthesis", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "PlantNetPhotosynthesis", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafNetPhotosynthesis", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafAbsorbedSWR", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafNetLWR", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafCi", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafIntrinsicWUE", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafVPD", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafStomatalConductance", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "LeafTemperature", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "Temperature", subdaily = TRUE), "ggplot")
  expect_s3_class(plot(S2, "PlantWaterBalance", subdaily = TRUE), "ggplot")
})

test_that("Can produce all basic growth plots",{
  examplesoil = soil(defaultSoilParams(2))
  control = defaultControl("Granier")
  control$verbose = FALSE
  x = forest2growthInput(exampleforestMED,examplesoil, SpParamsMED, control)
  G1<-growth(x, examplemeteo[d,], latitude = 41.82592, elevation = 100)
  
  expect_s3_class(plot(G1, "GrossPhotosynthesis"), "ggplot")
  expect_s3_class(plot(G1, "MaintenanceRespiration"), "ggplot")
  expect_s3_class(plot(G1, "CarbonBalance"), "ggplot")
  expect_s3_class(plot(G1, "SugarLeaf"), "ggplot")
  expect_s3_class(plot(G1, "StarchLeaf"), "ggplot")
  expect_s3_class(plot(G1, "SugarSapwood"), "ggplot")
  expect_s3_class(plot(G1, "StarchSapwood"), "ggplot")
  expect_s3_class(plot(G1, "SugarTransport"), "ggplot")
  expect_s3_class(plot(G1, "RootExudation"), "ggplot")
  expect_s3_class(plot(G1, "LeafPI0"), "ggplot")
  expect_s3_class(plot(G1, "StemPI0"), "ggplot")
  expect_s3_class(plot(G1, "SapwoodArea"), "ggplot")
  expect_s3_class(plot(G1, "LeafArea"), "ggplot")
  expect_s3_class(plot(G1, "SapwoodBiomass"), "ggplot")
  expect_s3_class(plot(G1, "LeafBiomass"), "ggplot")
  expect_s3_class(plot(G1, "FineRootBiomass"), "ggplot")
  expect_s3_class(plot(G1, "LabileBiomass"), "ggplot")
  expect_s3_class(plot(G1, "TotalLivingBiomass"), "ggplot")
  expect_s3_class(plot(G1, "SAgrowth"), "ggplot")
  expect_s3_class(plot(G1, "LAgrowth"), "ggplot")
  expect_s3_class(plot(G1, "HuberValue"), "ggplot")
})

test_that("Can produce all advanced growth plots",{
  examplesoil2 = soil(defaultSoilParams(4))
  control = defaultControl("Sperry")
  control$verbose = FALSE
  x2 = forest2growthInput(exampleforestMED,examplesoil2, SpParamsMED, control)
  G2<-growth(x2, examplemeteo[d,], latitude = 41.82592, elevation = 100)
  expect_s3_class(plot(G2, "FineRootArea"), "ggplot")
  expect_s3_class(plot(G2, "FRAgrowth"), "ggplot")
  expect_s3_class(plot(G2, "RootAreaLeafArea"), "ggplot")
})
