# Model inputs



## Soil description

### Soil physical description

Soil texture (i.e. percent of sand, silt and clay), bulk density and rock fragment content can differ between soil layers. Specifying a deep rocky layer is important because Mediterranean plants may extend their roots into cracks existing in the parent rock [@Ruffault2013]. In **medfate**,  soils can be described using between 1 and 5 soil layers. For each soil layer $s$ the following physical parameters are needed:

+ $d_{s}$ [`widths`]: Soil layer width (in mm).
+ $P_{clay,s}$ [`clay`]: Percent of clay.
+ $P_{sand,s}$ [`sand`]: Percent of sand.
+ $OM$ [`om`]: Percentage of organic mater per dry weight (can be missing).
+ $BD_{s}$ [`bd`]: Bulk density (in g/cm3) of each soil layer.
+ $P_{rocks,s}$ [`rfc`]: Percentage of rock fragment content (%).

Input data should be arranged in a data frame with soil layers in rows and variables in columns (see function `defaultSoilParams()`). The package provides a function to get soil information from [SoilGrids.org](https://soilgrids.org/) (see function `soilgridsParams()`) that can be helpful to those users lacking soil measurements corresponding to their target forest stands.

### Water retention curves

Water retention curve of a soil layer $s$ is the relationship between volumetric soil moisture, $\theta_s$ (in $m^3 \cdot m^{-3}$ of soil, excluding rock fragments), and the soil water potential, $\Psi_s$ (in MPa). This curve is characteristic for different types of soil, and is also called the *soil moisture characteristic curve*. Two water retention curve models are available in the package:

1. *Saxton model*: In this model, volumetric soil moisture $\theta(\Psi_s)$ corresponding to a given water potential $\Psi$ (in MPa) below $\Psi_{fc}$ is calculated using: 
\begin{equation}\theta(\Psi) = (\Psi/A)^{(1/B)}\end{equation}
where $A$ and $B$ depend on the texture and, if available, organic matter in the soil layer. If organic matter is available, $A$ and $B$ are calculated from $P_{clay}$, $P_{sand}$ and $OM$ following @Saxton2006. Otherwise, they are calculated from $P_{clay}$ and $P_{sand}$ as indicated in @Saxton1986. Volumetric changes between field capacity and saturation are estimated using a linear function.
2. *Van Genuchten model*: The well known van Genuchten [-@Genuchten1980] model is:
\begin{equation}\theta(\Psi) = \theta_{res}+\frac{\theta_{sat}-\theta_{res}}{\left[1+ (\alpha \cdot \Psi)^n \right]^{1-1/n}}\end{equation}
where $\theta(\psi)$ is the water retention, $\theta_{sat}$ is the saturated water content, $\theta_{res}$ is the residual water content, $\alpha$ is related to the inverse of the air entry pressure (and here has to be expressed in $MPa^{-1}$), and $n$ is a measure of the pore-size distribution.


### Soil initialization
Soil initialization is needed to estimate soil hydrological parameters from its physical description. Initialization is done using function `soil()`, which adds the following information to the physical soil description: 

+ $P_{macro, s}$ [`macro`]: Percentage of macroporosity corresponding to each soil layers. Macroporosity values are calculated for each soil layer using the equations given in @Stolf2011.
+ $\gamma_{soil}$ [`Gsoil`]: The maximum daily evaporation from soil($mm \cdot day^{-1}$).
+ $\kappa_{soil}$ [`Ksoil`]: Extinction parameter to regulate the amount of water extracted from each soil layer during bare soil evaporation.
+ $n_{s}$, $\alpha_{s}$, $\theta_{sat,s}$,$\theta_{res,s}$ [`VG_n`, `VG_alpha`, `VG_theta_sat`, `VG_theta_res`]: Parameters of the Van Genuchten-Mualem equations.

Parameters of the van Genuchten-Mualem model are estimated from the physical description of the soil using two kinds of pedotransfer functions (see help for `soil()`): 

1. Using the USDA texture classification and the average texture class parameters given by @Carsel1988.
2. Directly from the soil texture, organic matter and bulk density, using the pedotransfer functions in @Toth2015.

Users can also edit the `soil` object manually to provide user-defined parameters of the Van Genuchten retention curve.

### Water holding capacity and water table depth

Soil water holding capacity ($V_s$, in mm) in soil layer $s$ is defined as the volumetric water content at field capacity:
\begin{equation}
V_s = d_s\cdot ((100-P_{rocks,s})/100)\cdot\theta_{fc,s}
\end{equation}
where $d_s$ is the depth of the soil layer (in mm) and $P_{rocks,s}$ is the percentage of rock fragments. Thus, soil water holding capacity depends on the water retention curve used to determine $\theta_{fc} = \theta(-0.033)$. Soil water content at saturation is calculated anagolously, but replacing $\theta_{fc,s}$ by $\theta_{sat,s}$. Similarly water content at wilting point (-1.5 MPa) is calculated replacing $\theta_{fc,s}$ by $\theta_{wp,s}$ where $\theta_{wp} = \theta(-1.5)$. The amount of extractable water is difference between water content at field capacity and a the water content at a minimum water potential, which can be set at wilting point or lower values (by default at -5 MPa).

Water table depth ($WT$, in mm) equals soil depth when all soil layers are below field capacity. When some layers are between field capacity and saturation, water table depth is calculated as:
\begin{equation}
WT = \sum_{s}{d_s \cdot \min\left[1,(\theta_{sat,s} - \theta(\Psi_s))/(\theta_{sat,s}-\theta_{fc,s})\right]}
\end{equation}


## Vegetation description

Representation of vegetation is not spatially-explicit in **medfate** (i.e. trees or shrubs do not have explicit coordinates within forest stands). However, differences in tree or shrub size (i.e. height) are explicitly taken into account. The taxonomic identity of plants is also considered, and parameter values need to be provided for each taxonomic entity (but the package could be used with functional groups). This representation is chosen so that package functions can be easily applied to forest plot data, for example from national forest inventories. 

Vegetation in the stand is described using a set of plant cohorts, in an object
of class `spwbInput`. Each plant cohort $i$ is primarly defined by its
species identity ($SP_i$; with R name [`SP`]).

### Aboveground parameters

The aboveground structure if each cohort is defined using a set attributes defined in the following table, where columns **spwb** and **growth** indicate whether attributes are required by functions `spwb()` and `growth()`, respectively:

| Symbol | Units | R  | Description                        | spwb | growth |
|--------|-------|----| ------------------------------------|-----|-----|
| $H_i$  | $cm$  | `H` | Total tree or shrub height |  Y  |  Y  |
| $CR_i$ |       | `CR`| Crown ratio (i.e. ratio between crown length and total height) | Y | Y |
| $N$ | $ind · ha^{-1}$ | `N` | The density of tree individuals | N | Y |
| $DBH$ | $cm$ | `DBH` | Tree diameter at breast height | N | Y |
| $Cover$ | % | `Cover` | Shrub percent cover | N | Y |
| $LAI^{live}_i$ | $m^2 \cdot m^{-2}$ | `LAI_live` | (Maximum) leaf area index | Y | Y |
| $LAI^{dead}_i$ | $m^2 \cdot m^{-2}$ | `LAI_dead` | Dead leaf area index | Y | Y |
| $LAI^{\phi}_i$ | $m^2 \cdot m^{-2}$ | `LAI_expanded` | Current expanded leaf area index | Y | Y |

Height values refer to average height of individuals included in the cohort, and the same for crown ratio and $DBH$. $LAI$ variables refer to one-side leaf area of plants in the cohort per surface area of the stand. While plant height is relatively easy to measure, it is normally quite hard to estimate leaf area indices for stands and species. Package **medfate** provides some utilities to provide estimates crown ratio and $LAI$ from forest inventory data (e.g. heights, DBH and density for measured trees), using allometric relationships calibrated for catalonia (see chapter \@ref(leafbiomass)).

Vegetation characteristics stay constant during simulations using function `spwb()`, although the actual expanded leaf area and dead leaf area may vary is the species is winter deciduous. Function `growth()` can modify any of the vegetation attributes.


### Belowground parameters

The root system of each plant cohorts is described using the proportion of fine
roots in each soil layer:

+ $v_{i,s}$ [`V[i,s]`]: The proportion of fine roots in each soil layer $s$.

The rooting system of each cohort $i$ (i.e. the proportions $v_{i,s}$) can be defined assuming conic distribution of fine roots (see `root_conicDistribution()`). In this case, only rooting depth parameter is needed to determine fine root proportions. Alternatively, one can adopt the linear dose response model (Collins and Bras, 2007; Schenk and Jackson, 2002): 
\begin{equation}
Y_i(z)=\frac{1}{1+(z/Z_{50,i})^{c_i}}
\end{equation}
where $Y_i(z)$ is the cumulative fraction of fine root mass located between surface and depth $z$; $Z_{50,i}$ is the depth above which 50% of the root mass is located; and $c_i$ is a shape parameter related to $Z_{50,i}$ and $Z_{95,i}$ as $c_i  = 2.94 / \ln(Z_{50,i} / Z_{95,i})$ (see `root_ldrDistribution()`). 

```{r, echo = FALSE, fig.width=7, fig.height=4, fig.cap = "Examples of root density profile according to a conic distribution (left) and the linear dose response model (right)."}
par(mar=c(4,4,1,1), mfrow=c(1,2))
P = root_conicDistribution(c(200,1500), rep(10,151))
matplot(x=t(P)*10, y=seq(0,1500, by=10), type="l", xlim=c(0,2), ylim=c(1500,0), ylab = "Depth (mm)", 
        xlab="Percentage of fine roots/mm")
legend("bottomright", legend=c("Z = 200", 
       "Z = 1500"), col=c("black","red"), lty=1:2, bty="n")
P = root_ldrDistribution(c(100,500), c(200,1500), rep(10,151))
matplot(x=t(P)*10, y=seq(0,1500, by=10), type="l", xlim=c(0,2), ylim=c(1500,0), ylab = "Depth (mm)", 
        xlab="Percentage of fine roots/mm")
legend("bottomright", legend=c("Z50 = 100, Z95 = 200", 
       "Z50 = 200, Z95 = 1500"), col=c("black","red"), lty=1:2, bty="n")
```


## Metereological input {#meteoinput}
Weather input data must include variables calculated at the **daily** scale. Data should be arranged in a data frame with days in rows and variables in columns. The following table indicates the symbols, units, definitions and the variable name in R.

| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $T_{mean}$ | $^{\circ} \mathrm{C}$ | `MeanTemperature` | Mean temperature |
| $T_{min}$ | $^{\circ} \mathrm{C}$ | `MinTemperature` | Minimum temperature |
| $T_{max}$ | $^{\circ} \mathrm{C}$ | `MaxTemperature` | Maximum temperature |
| $RH_{min}$ | % | `MinRelativeHumidity` | Minimum relative humidity |
| $RH_{max}$ | % | `MaxRelativeHumidity` | Maximum relative humidity |
| $P$ | $L \cdot m^{-2} = mm$ | `Precipitation` | Precipitation |
| $PET$ | $L \cdot m^{-2} = mm$ | `PET` | Potential evapotranspiration, preferably calculated using Penman's equation |
| $Rad$ | $MJ \cdot m^{-2}$ | `Radiation` | Solar radiation after accounting for clouds |
| $u$ | $m \cdot s^{-1}$ | `WindSpeed` | Wind speed |

Not all models require all weather variables, this will be indicated in the corresponding model chapters. For convenience, we recommend meteorological input to be generated using package **meteoland** [@DeCaceres2018].


## Control parameters
Control parameters are a list of parameter values, initialized using function `defaultControl()`, that the user can modify to change the general behavior of model functions. Not all control parameters are relevant to all model functions