# (PART) Basic water balance modelling {-}

# Basic water balance model {#basicwaterbalance}

This chapter provides an overview of the water balance model described in @DeCaceres2015, which allows simulating the temporal variation in soil moisture on a daily step basis for a given forest stand and for the period corresponding to input weather data. While the information provided in this chapter should be enough to understand what the model does and when it can be useful, the following ones provide a deeper understanding on how the different processes are formulated.

## Design principles

The model considers only the vertical spatial dimension of the stand and not the horizontal distribution of plants within it. In other words, the model is not spatially explicit (i.e., plants do not interact for space explicitly). Still, the stand is divided into groups of plants, here referred to as *plant cohorts* of different species, height and leaf area index ($LAI$). Height and $LAI$ values determine competition for light. $LAI$ values also drive competition for water, along with root distribution. The soil water balance follows the design principles of SIERRA [@Mouillot2001;@Ruffault2014;@Ruffault2013] and BILJOU [@Granier1999;-@Granier2007], although some features are taken from other models [@Kergoat1998]. Potential evapotranspiration ($PET$) is a required input and the model determines maximum canopy transpiration ($Tr_{\max}$) using an empirical relationship between the $LAI$ of the stand and the ratio $Tr_{\max}/PET$ [@Granier1999]. Actual plant transpiration is estimated using a function that depends on current soil moisture levels, cohort-specific drought resistance, fine root distribution and the degree of shading of the target plant cohort.


## State variables
The following are state variables in the model:

+ Cumulative growth degree days, $GDD$, are tracked by the model and determine leaf phenological status of winter deciduous species.
+ Daily soil moisture content dynamics on each layer $s$ are tracked using $W_s = \theta_s(\Psi)/ \theta_{fc,s}$, the **proportion of volumetric soil moisture in relation to field capacity**, where field capacity, $\theta_{fc,s}$, is assumed to correspond to $\Psi_{fc} = -0.033$ MPa. Note that $W_s$ values larger than one are possible if the soil is between field capacity and saturation (which can happen if deep drainage is not allowed).
+ If snow accumulation/melting is considered, the model tracks $S_{snow}$, the snow water equivalent (in mm) of the snow pack storage over the surface.
+ If irreversible cavitation is activated, the model tracks $P_{embolized,i}$, the maximum value of daily drought stress so far experienced.


## Water balance
Daily variations in soil water content ($\Delta{V_{soil}}$ in $mm$) can be summarized as:

\begin{equation}
\Delta{V_{soil}} = Pr + Sm - In - Ru - Dd - Es -Tr
(#eq:basicwaterbalanceequation)
\end{equation}

where $Pr$ is precipitation as rainfall, $Sm$ is water from melting the snow pack (if considered), $In$ is the interception loss (i.e., water evaporated after being intercepted by the canopy), $Ru$ is surface runoff, $Dd$ is deep drainage (i.e. water percolated to layers beyond soil depth), $Es$ is evaporation from soil and $Tr$ is plant transpiration. 

If snow dynamics are considered, the water balance of the snow pack ($\Delta{S_{snow}}$ in $mm$ of snow water equivalents) is defined as:

\begin{equation}
\Delta{S_{snow}} = Ps - Sm
\end{equation}

where $Ps$ is precipitation as snowfall and $Sm$ is snow melt. Evaporation from bare soil cannot occur if there is a snow pack over the soil (i.e., if $S_{snow}>0$ then $Es = 0$).

## Process scheduling

Every day, water balance is simuilated using the following steps:

  1. Update leaf area values according to the phenology of species and recalculate light extinction (sections \@ref(leafphenology) and \@ref(basiclightextinction)).
  2. If snow dynamics are included, increase snow pack from snow precipitation ($Ps$) and decreases it from snow melting ($Sm$) (section \@ref(snowpack)).
  3. Determine rainfall interception loss ($In$) and net rainfall ($Pr_{net}$) (section \@ref(interception))
  4. Increase soil water content due to net rainfall ($Pr_{net}$), surface runon ($Ro$) and snow melting ($Sm$), after accounting for surface runoff ($Ru$) and deep drainage ($Dd$) (section \@ref(runoff)).
  5. Decrease soil water content due to bare soil evaporation ($Es$), if snow is not present (section \@ref(soilevaporation)).
  6. Determine transpiration, photosynthesis and drought stress for each plant cohort  and decrease water content due to plant transpiration ($Tr$) (chapter \@ref(transpirationgranier)).

Details of the formulation of each of these processes are provided within the referred chapters and sections.

## Inputs and outputs

### Soil, vegetation and meteorology

**Soil**

Soil input requirements are fully described in section \@ref(soilinput).

**Vegetation**

Vegetation input requirements are fully described in section \@ref(vegetationinput). Trees and shrubs do not need to be distinguished in soil water balance calculations, since both kinds of cohort have a $LAI$ value. In most cases, users only need to estimate the leaf area index corresponding to live leaves, i.e. $LAI^{live}$, because normally at the starting point all leaves are expanded (i.e. $LAI^{\phi} = LAI^{live}$) and one can assume no dead leaves in the canopy (i.e., $LAI^{dead} = 0$). Vegetation characteristics stay constant during simulations using function `spwb()`, although the actual expanded leaf area ($LAI^{\phi}$) and dead leaf area may vary is the species is winter deciduous.

**Meteorology**

The minimum weather variables required to run the model are mean temperature ($T_{mean}$), precipitation ($P$) and potential evapotranspiration ($PET$). Solar radiation ($Rad$) is required if snow pack dynamics have to be simulated. Additionally, the user may also specify values of wind speed ($u$) that are used to control leaf fall in autumn. Definitions and units of these variables are given in section \@ref(meteoinput).

### Vegetation functional parameters

Vegetation functional attributes are normally filled for each cohort by function `spwbInput()` from species identity. However, different parameters can be specified for different cohort of the same species if desired (see function `modifyCohortParams()`). Functional parameters relate to light extinction, water interception and leaf phenology (`paramsBase`):

| Symbol | Units | R  | Description                                  | 
|--------|-------|----| ---------------------------------------------|
| $k_{PAR,i}$ | | `k` | PAR extinction coefficient |
| $s_{water, i}$ | $mmH_2O·LAI^{-1}$ | `g` | Crown water storage capacity (i.e. depth of water that can be retained by leaves and branches) per LAI unit. |
| $S_{GDD,i}$ | $^{\circ} \mathrm{C}$ | `Sgdd` | Growth degree days corresponding to leave budburst|
| $\Psi_{extract,i}$ | MPa | `Psi_Extract` |  The water potential at which whole plant conductance is 50% of maximum |
| $WUE_{\max,i}$ | $g C \cdot mm^{-1}$ |  `WUE` |  Maximum water use efficency |
| $K_{rootdisc,i}$ | [0-1] |  `pRootDisc` |  Whole-plant relative conductance corresponding to hydraulic disconnection from the soil |

### Control parameters
The control values relevant for the simple water balance model are:

+ `verbose [=TRUE]`: Whether extra console output is desired during simulations.
+ `soilFunctions [= "SX"]`: Water retention curve model, either "SX" (for Saxton) or "VG" (for Van Genuchten).
+ `leafPhenology [= TRUE]`:  Whether leaf phenology is simulated.
+ `snowpack [= TRUE]`:  Whether dynamics of snow pack are included.
+ `drainage [= TRUE]`:  Whether water exceeding the field capacity of the bottom layer is lost by deep drainage into a non-reachable compartment.
+ `transpirationMode [= "Granier"]`: Transpiration model, in this case "Granier".
+ `defaultWindSpeed [= 2.5]`: Default value for wind speed (in $m \cdot s^{-1}$) when this is missing (only used for leaf fall).
+ `cavitationRefill [= TRUE]`: If `FALSE` the model operates in a irreversible cavitation mode.

### Model output
Function `spwb` returns a list object whose elements are data tables. Each table has dates as rows and has different output variables:

+ `WaterBalance`: Components of the climatic and soil daily water balance (i.e. net precipitation, infiltration, runoff, plant transpiration...).
+ `Soil`: Daily variation of soil variables  (volume, moisture relative to field capacity, water potential) for each soil layer.
+ `PlantLAI`: Daily values leaf area index for each plant cohort.
+ `PlantTranspiration`: Daily transpiration (in $mm$) for each plant cohort.
+ `PlantPhotosynthesis`: Daily net photosynthesis (in $g C \cdot m^{-2}$) for each plant cohort.
+ `PlantPsi`: Daily water potential of each plant (in MPa).
+ `PlantStress`: Daily stress level suffered by each plant cohort (relative whole-plant conductance).

The output of simulations can be inspected using specific `plot` and `summary` functions (see the corresponding package *vignette*).

## Applications

The basic water balance model is relatively easy to parametrize and use. These features make it appropriate for applications that do not seek a high predictive at the plant level, but require robust estimates at the stand level. In our opinion the basic water balance model may be useful for the following applications: 

1. To monitor or forecast temporal variation in soil water content in particular stands. 
2. Monitor or forecast temporal variation of plant drought stress in particular stands (for example to anticipate mortality events).

For example, @Karavani2018 employed the water balance to provide sound estimates of soil moisture dynamics to predict mushroom production in a network forest stands. The model is particularly interesting to test the relationship between forest structure/composition and the water balance at the stand level or the drought stress suffered by plants, as done in @Ameztegui2017. See also another application in @Rolo2019.
