# Leaf phenology and light extinction {#leafphenologylight}


## Leaf phenology and leaf fall 

Given a base temperature ($T_{base} = 5^{\circ} \mathrm{C}$), the growth degree days ($GDD$) are zero for all those days where mean temperature $T_{mean}$ is below $T_{base}$ and start increasing when temperatures become warmer than this threshold. In other words, the $GDD$ function accumulates $\max(0.0, T_{mean} - T_{base})$ for all days previous to the current one. At the end of a year the cummulative value is set again to zero. Plant species can have either *evergreen* or *winter-deciduous* phenology. Evergreen plants maintain constant leaf area over the year, whereas in deciduous plants leaf-phenological status is updated daily, represented by $\phi_i$, the fraction of maximum leaf area. Leaf area index (LAI) values of deciduous plants are adjusted for leaf phenology following [@Prentice1993; @Sitch2003]:

\begin{equation}
LAI_{i}^{\phi}=LAI^{live}_i\,\cdot\phi_i
\end{equation}

Budburst occurs when daily temperature exceeds $T_{base}$ and $\phi_i$ increases
linearly from 0 to 1 as function of the degree days above $T_{base}$, until a the
value $S_{GDD,i}$ is reached (i.e. until $GDD > S_{GDD,i}$). In autumn, $\phi_i$
drops to 0 when average daily temperature falls again below $T_{base}$ [@Sitch2003]. The drop of $\phi_i$ causes live expanded leaves to become dead leaves. To avoid a sudden decrease of leaf area, dead leaves are kept in the canopy and they are reduced daily using a negative exponential function of wind speed:
\begin{equation}
LAI^{dead}_i=LAI^{dead}_i\,\cdot e^{- u/10}
\end{equation}
where $u$ is wind speed in ($m \cdot s^{-1}$).

After updating the leaf area of each cohort, the model updates the total leaf area of the stand. To simplify the notation, let us call $LAI^{all}_{i}$ the sum of dead and live expanded leaves of a cohort $i$:
\begin{equation}
LAI^{all}_{i} = LAI^{\phi}_{i}+LAI^{dead}_{i}
\end{equation}
If there are $c$ plant cohorts, the leaf area index of the whole stand, $LAI_{stand}$
is then:
\begin{equation}
LAI_{stand} = \sum_{i=1}^c{LAI_{i}^{all}}
\end{equation}

Although simulations will normally start in winter and $GDD$ will be zero at the beginning, the user can specify a starting non-zero value for $GDD$ in the object created by function \texttt{spwbInput()}.

## Light extinction
The proportion of photosynthetic active radiation (PAR) decreases with leaf area following thee Beer-Lambert’s light extinction equation. To calculate the proportion of PAR available for a given plant cohort one must accumulate the light extinction caused by cohorts whose crown is above that of the target cohort:
\begin{equation}
L^{PAR}_i=e^{-\sum_{h=1}^{c}{k_{PAR,h} \cdot LAI_{h}^{all} \cdot p_{ih}}}
\end{equation}
where $k_{PAR,h}$ is the PAR extinction coefficient of cohort $h$. Because plant
cohorts may differ in height only slightly, leaf area is multiplied by $p_{ih}$,
the proportion of the crown of cohort $h$ that overtops that of cohort $i$: 
\begin{equation}
p_{ih}=\max(0,\min(1,(H_h-H_i\cdot (1 - CR_i))/(H_h-H_h\cdot (1 - CR_h))))
\end{equation}
where $CR_i$ and $CR_h$ are the crown ratio of cohorts $i$ and $h$. In other terms,
cohorts whose crown is completely above that of $i$ reduce the amount of light
available more strongly by than cohorts that are only slightly taller.
$L^{PAR}_{ground}$, the proportion of PAR that reaches the ground, is calculated as:
\begin{equation}
L^{PAR}_{ground}=e^{-\sum_{i=1}^{c}{k_{PAR,i} \cdot LAI_{i}^{all}}}
\end{equation}

The shortwave radiation (SWR; 400-3000 nm) energy absorbed by each plant cohort
needs to be calculated to determine plant transpiration, and the radiation absorbed
by the soil is needed to calculate soil evaporation. Foliage absorbs a higher
proportion of PAR than SWR; thus, the extinction coefficient is higher for PAR
than for SWR. However, values for the ratio of extinction coefficients are rather
constant. Following Friend et al. [-@Friend1997] here it is assumed that the extinction
coefficient for PAR is 1.35 times larger than that for SWR (i.e.
$k_{SWR,i} = k_{PAR,i}/1.35$). 

To calculate radiation absorption, where the vertical dimension of the plot is
divided into 1 m deep layers, and the SWR absorbed is calculated for each plant
cohort in each layer. Let $n$ be the number of canopy layers. The fraction of
radiation incident on layer $j$ that is absorbed in the same layer is:
\begin{equation}
f_j=1 - e^{-\sum_{i=1}^{c}{k_{SWR,i} \cdot LAI_{i,j}^{all}}}
\end{equation}
where $LAI_{i,j}^{all} = LAI_{i,j}^{\phi}+LAI_{i,j}^{dead}$ is the leaf area
index of cohort $i$ in layer $j$. Hence, the fraction transmitted is $(1-f_j)$.
The fraction of radiation incident on layer $j$ that is absorbed by expanded leaves
of plant cohort $i$ in that layer ($f_{ij}$) is calculated from the relative
contribution of these leaves to the total absorption in the layer:
\begin{equation}
f_{ij} = f_j \cdot \frac{k_{SWR,i}\cdot LAI_{i,j}^{\phi}}{\sum_{h=1}^{c}{k_{SWR,h} \cdot LAI_{h,j}^{all}}}
\end{equation}
The fraction of canopy radiation absorbed by a plant cohort $i$ across all layers
is found by adding the fraction absorbed in each layer:
\begin{equation}
f_i = \sum_{j=1}^{n}{f_{ij}\cdot \prod_{h>j}^{n}{(1-f_h)}}
\end{equation}
where for each layer the fraction of the radiation incident in the canopy that
reaches the layer is found by multiplying the transmitted fractions across the
layers above it. The proportion of (shortwave) net radiation absorbed by the
ground is simply:
\begin{equation}
L^{SWR}_{ground} = 1 - \sum_{j}^{n}{f_j}
\end{equation}


