# Subdaily temperature and light variations {#subdailytemplight}

## Air temperature
Diurnal above-canopy air temperature ($T_a$) variations are modeled assuming a sinusoidal pattern with $T_a = T_{\min}$ at sunrise and $T_a = (T_{\min}+T_{\max})/2$ at sunset. Air temperature varies linearly between sunset and sunrise [@McMurtrie1990].


## Diffuse and direct radiation
Daily global radiation (in MJ·m$^{-2}$) is assumed to include both direct and diffuse shortwave radiation (SWR). Using latitude information and whether is a rainy day, this quantity is partitioned into instantaneous direct and diffuse SWR and PAR for different daily substeps. Values of instantaneous direct and diffuse SWR and PAR above the canopy (i.e. $I_{beam}$ and $I_{dif}$) are calculated using the methods described in @Spitters1986, which involve comparing daily global radiation with daily potential radiation. 

## Longwave radiation
Longwave radiation (LWR) coming from the atmosphere is calculated following @Campbell1998:
\begin{equation}
L_{a} = \epsilon_{a} \cdot \sigma \cdot (T_{a} + 273.16)^{4.0}
\end{equation}
where $T_{a}$ is air temperature, $\sigma = 5.67 \cdot 10^{-8.0}$  W·K$^{-4}$·m$^{-2}$ is the Stephan-Boltzmann constant and $\epsilon_{a}$ is the emmissivity of the atmosphere, calculated using:
\begin{eqnarray}
\epsilon_{a} &=& (1 - 0.84 \cdot c) \cdot \epsilon_{ac} + 0.84 \cdot c \\
\epsilon_{ac} &=& 1.72 \cdot \left(\frac{vp_{day}}{T_{a} + 273.16} \right)^{1/7}
\end{eqnarray}
where $vp_{day}$ is the average daily vapor pressure (in kPa) and $c$ is the proportion of clouds. 