# Closing canopy and soil energy balances {#closecanopysoilenergybalance}

## Convective energy
Convective energy fluxes between atmosphere and the canopy ($H_{ca}$) and between the canopy and the soil ($H_{cs}$) are determined as follows:
\begin{eqnarray}
H_{ca} &=& \frac{\rho_{a} \cdot c_p}{r_{ca}}\cdot (T_{can} - T_a) \\
H_{cs} &=& \frac{\rho_{c} \cdot c_p}{r_{cs}}\cdot (T_{can} - T_{soil})
\end{eqnarray}
where $\rho_{a}$ and $\rho_{c}$ are the air density above-canopy and inside-canopy, respectively, $c_{p}$ = 1013.86 $J路kg^{-1}路C^{-1}$ is the specific heat capacity of the air. $r_{ca}$ and $r_{cs}$ are the atmosphere-canopy and canopy-soil aerodynamic resistances (in $s路m^{-1}$). These, in turn, are calculated using canopy height, total LAI and above-canopy and below-canopy wind speeds.

## Latent heat
As mentioned above, the model only considers latent heat exchanged from plant transpiration, neglecting energy fluxes corresponding to evaporation from the soil and evaporation of rain intercepted by the canopy. After determining stomatal regulation and transpiration for each plant cohort, latent heat of transpiration is simply calculated as:
\begin{equation}
LE_{c} = \lambda_{T_{can}} \sum_{i}{E_i}
\end{equation}
where $\lambda_{T_{can}}$ is the latent heat of vaporization at temperature $T_{can}$ (in J路kg$^{-1}$) and $E_i$ is the instanteous transpiration flux calculated for cohort $i$.

## Canopy capacitance and temperature changes

TO BE DONE

## Soil temperature changes

Instantaneous soil temperature changes on each soil layer depend on the balance between incoming and outcoming energies ($G_k$ and $G_{k-1}$):
\begin{equation}
\frac{\delta T_{soil,k}}{\delta t} = \frac{G_k - G_{k-1}}{C_{soil,k} \cdot \Delta z_k}
\end{equation}
where $\Delta z_k$ is the soil width of layer $k$ and $C_{soil,k}$ is the thermal capacity of layer $k$, depending on soil moisture and texture (see function `soil_thermalcapacity`).

Energy inflow to the first layer (i.e. $G_0$) is the result of the soil energy balance explained above, while energy transfers between layers (i.e. $G_k$) depend on the soil temperature gradient:
\begin{eqnarray}
G_0 &=& K_{abs,sa} + L_{abs,sa} - L_{em,s} + L_{abs,sc} + H_{cs}\\
G_k &=& \lambda_{soil,k} \cdot \frac{\delta T_{soil,k}}{\delta z}
\end{eqnarray}
where $\lambda_{soil,k}$ is the thermal conductivity of layer $k$, depending on soil moisture and texture (see function `soil_thermalconductivity`). The gradient in the bottom layer is calculated assuming a temperature of the earth (at 10 m) of 15.5 Celsius.

