# (PART) Forest growth modelling {-}

# Forest growth model

## Design principles

The physical structure of the stand is represented in one (vertical) dimension. Height (or depth) is the only dimension that matters (i.e. the coordinates of plants are not explicit). The model is cohort-based, meaning that similar plant individuals are represented using a single entity with average properties (e.g. tree height or diameter) and a density variable is used to scale from individual level to the cohort level. Processes are implemented either at the cohort-level (water balance and photosynthesis) or at the individual level (carbon balance and growth). The model has been designed to be executed on forest inventory plots, but it can be run on other kind of vegetation (e.g. shrublands or crops) provided vegetation is described using the appropriate variables (i.e. diameter and height for trees, percent cover and height for shrubs). The model tries to reproduce the physiological processes that modulate leaf area changes and plant growth rates. Nevertheless, since the model does not implement all processes that may affect growth (such as nutrient availability), maximum growth rates and maximum plant sizes are constrained from user inputs, to ensure that model can be more easily calibrated and validated with observations. Consequently, we believe the model is suited to study variations of plant growth derived from environmental conditions and competition for light and water.

Leaf area of each plant cohort is divided between live (wether in resistance buds or unfolded leaves) and dead (standing dead trees). Expanded leaf area corresponds to the portion of live leaf area that is unfolded at any given moment through the leaf phenological cycle. Leaf area density of individuals is considered constant across the crown. Sapwood area of individuals is another important state variable. The Pipe model [@Shinozaki1964] is adopted to link increments of leaf area, sapwood area and fine root biomass. Ratios of leaf area to sapwood area (Huber value) can vary within species, due to environmental conditions [@Mencuccini1995]. The model assumes a constant, species-specific Huber value, but allows deviations from the pipe model caused by drought-related leaf area reductions. 

Water fluxes, soil water balance and plant photosynthesis processes follow the design of the soil water balance model and this part of the model design will not be repeated here. Plant respiration is calculated at the individual level, by estimating the respiration of leaves, stem and fine root compartments. While fine root respiration is proportional to leaf respiration, and hence to expanded leaf area, stem respiration depends on plant size.

Growth is determined taking into account environmental limitations on both source (i.e. carbon assimilation) and sink (i.e. carbon investment on plant tissue expansion) [@Fatichi2014; @Guillemot2015; @Korner2015]. With respect to carbon availability for growth, the model offers three alternatives. In the first one, carbon available for growth is simply the daily difference between net photosynthesis and maintenance respiration (i.e. no carbon storage). The second alternatives involves a single (fast) carbon storage pool that allows decoupling assimilation from growth. Finally, the third alternative involves two carbon storage pools ('fast' and 'slow') with a transfer rate between them [@Richardson2013; @Dietze2014], which we assume to be regulated by the need to maintain, as much as possible, a minimum amount of carbon in the fast pool (i.e. for metabolic and osmotic purposes). In the second and third modes, maximum overall C storage capacity is proportional to plant size.

The LPG model [@Sitch2003] applies different turnover rates for different tissues, but then tries to satisfy the pipe model [@Shinozaki1964] by allocating C where it is more limiting. Instead, we assume that baseline leaf and fine root turnover rates are linearly related to conversion from sapwood to heartwood. Similarly to 3-PG [@Landsberg1997] we assume that the turnover rate is smallest for young plants, and it increases up to a maximum value. The model assumes that plants cannot suffer from cavitation if the leaf water potential is large enough for growth to occur (i.e. if cell turgidity is large enough for cell elongation). Similarly, it also assumes that growth stops before cavitation starts during drought events. When sapwood area reduction occurs, this not only reduces leaf area, but also decreases the amount of fast C reserves available for future growth. Thus it is assumed that parts of the plant are effectively disconnected.

Tree structural variables are updated as in forest gap models [@Lindner1997].

## State variables



## Process scheduling
Every day the growth model first updates the expanded leaf area of living plants according to the phenology of species and the day of the year. Then the model performs soil water balance, transpiration and photosynthesis calculations by calling the soil water balance submodel. After dealing with water fluxes and photosynthesis, the model determines the amount of respiratory biomass, the maximum storage value per individual and maintenance respiration at the individual level. The comparison between photosynthesis and respiration leads to an amount of carbon available for growth (if no carbon pools are considered) or a change in the amount of fast carbon storage pool (if one or two carbon pools are considered). After that, the model determines variations in sapwood area, dead leaf area and live leaf area, which can originate due to conversion from sapwood to heartwood, growth or drought-induced cavitation. If two carbon storage pools are considered, at the end of the day the model determines the direction and amount of carbon transfer between them. Once a year (or by the end of the simulated period) the model translates sapwood area growth into structural variables (i.e., plant height, tree DBH, tree crown ratio and shrub cover). 


### Water balance, plant transpiration and photosynthesis
The growth model calls the soil water balance model as a submodel to perform soil water balance and photosynthesis calculations. We only summarize the steps here. The submodel first increases soil moisture due to precipitation, accounting for canopy interception loss, surface runoff and deep drainage. To calculate water losses due to transpiration, the submodel acts differently depending on whether  transpiration mode is set to 'Granier' or 'Sperry'. Generally speaking, though, the submodel determines stomatal conductance of each plant cohort according to the environmental conditions (i.e. light, leaf temperature, water vapor deficit and soil moisture) and this leads to an estimation of transpiration and net photosynthesis. The submodel then decreases water content due to bare soil evaporation, and plant transpiration, which completes the daily water balance. 

 Among other outputs, the soil water balance submodel provides values of leaf water potential $\Psi_{leaf}$ (in MPa) and net photosynthesis calculated at the plant cohort level, $A_n^{coh}$ (in $g C · m^{-2} · day^{-1}$).  $\Psi_{leaf}$ is used in the growth model to modulate drought effects on growth and leaf area losses (see below), whereas $A_n$ is obviously needed to determine carbon balance and growth. Since carbon balance is calculated at the individual level, $A_n^{coh}$ needs to be scaled to net photosynthesis per individual (in $g C · ind^{-1} · day^{-1}$) using:
\begin{equation}
A_{n}^{ind} = 10000 \cdot A_n^{coh} / N
\end{equation}
where $N$ is the density of individuals per hectare.


## Model input


### Vegetation state variables and parameters

Vegetation in the stand is described using a set of plant cohorts, described in an object of class `growthInput`. This function assembles all parameters needed for the simulation of a given stand in a single list. Model parameters are grouped by category.  Regarding physical aboveground description of the stand, each plant cohort is defined by its species identity ($SP$; with R name [`SP`]). In addition, each cohort needs to be defined regarding the following state variables:

+ $N$ [`N`]: The density of individuals (in $ind · ha^{-1}$).
+ $DBH$ [`DBH`]: Tree diameter at breast height (in cm).
+ $Cover$ [`Cover`]: Shrub percent cover (in %).
+ $H$ [`H`]: Total tree or shrub height (in cm).}
+ $CR$ [`CR`]: Crown ratio (i.e. the ratio between crown length and total height).}
+ $LAI^{live}$ [`LAI_live`]: Live leaf area index (one-side live leaf area of plants in the cohort per surface area of the stand) (in m$^2$·m$^{-2}$).}
+ $LAI^{\phi}$ [`LAI_expanded`]: Expanded leaf area index (one-side expanded leaf area of plants in the cohort per surface area of the stand) (in m$^2$·m$^{-2}$).}
+ $LAI^{dead}$ [`LAI_dead`]: Dead leaf area index (one-side dead leaf area of plants in the cohort per surface area of the stand) (in m$^2$·m$^{-2}$).}
+ $LAI^{predrought}$ [`LAI_predrought`]: Live leaf area index before the current drought started (one-side dead leaf area of plants in the cohort per surface area of the stand) (in m$^2$·m$^{-2}$).}
+ $SA$ [`SA`]: Area of functional sapwood per individual (in cm$^2$·ind$^{-1}$).}
+ $C_{fast}$ [`fastCstorage`]: Amount of C in the fast carbon storage pool (in g C·ind$^{-1}$).}
+ $C_{slow}$ [`slowCstorage`]: Amount of C in the slow carbon storage pool (in g C·ind$^{-1}$).}

Excepting $SP$ (species identity) and $N$ (density), the remaining aboveground state variables are modified during growth simulations. Belowground parameters are the following:

+ $Z$ [`Z`]: The rooting depth (in cm).}
+ $V$ [`V`]: A matrix with the proportion of fine roots in each soil layer.}

Additional belowground variables are included if `transpirationMode = "Complex"}. These, and the parameters needed for water balance calculations are described in vignette '\textbf{Soil description and root system architecture}'. 

The following physiological parameters are needed for growth calculations:

+ $SLA$ [`SLA`]: Specific leaf area (m$^2$·kg$^{-1}$).
+ $Hv$ [`Al2As`]: Huber value. Leaf area to sapwood area ratio (in m$^2$·m$^{-2}$).}
+ $W_{dens}$ [`WoodDens`]: Wood density (at 0\% humidity) (in g·cm$^{-3}$).}
+ $W_{C}$ [`WoodC`]: Wood carbon content in relation to dry weight (in g·g$^{-1}$).}
+ $C_{p,\max}$ [`Cstoragepmax`]: Maximum storage capacity, expressed as C per total respiratory C (in gC·gC$^{-1}$).
+ $RGR_{\max}$ [`RGRmax`]: Maximum daily relative growth rate (in sapwood area basis) (in cm$^2$·cm$^{-2}$).

Another set of parameters is needed to transform changes in sapwood area and leaf area to changes in the structural variables such as tree height, tree crown ratio or shrub cover:

+ $H_{\max}$ [`Hmax`]: Maximum plant height (in cm).
+ $f_{HD,\min}$, $f_{HD,\max}$ [`fHDmin}, `fHDmax`]: Minimum and maximum values of the height-diameter ratio (in cm·cm$^{-1}$).
+ $Z_{\max}$ [`Zmax`]: Maximum rooting depth (in mm).
+ $a_{ash}$ [`Aash`]: Regression coefficient for the quadratic relationship between shrub height and shrub area.
+ $a_{bsh}$, $b_{bsh}$ [`Absh`, `Bbsh`]: Allometric coefficients relating crown phytovolume with dry weight of shrub individuals.
+ $CR$ [`cr`]: Ratio between crown length and total height (constant value for shrubs).
+ $r_{6.35}$ [`r635`]: Ratio between the dry weight of leaves plus branches and the dry weight of leaves alone for branches of 6.35 mm of diameter.
+ $a_{cr}$, $b_{1cr}$, $b_{2cr}$, $b_{3cr}$, $c_{1cr}$, $c_{2cr}$ [`B1cr`, `B2cr`, `B3cr`, `C1cr`, `C2cr`]: Regression coefficients used to update the crown ratio of trees.
+ $a_{cw}$, $b_{cw}$ [`Acw`, `Bcw`]: Regression coefficients used to calculate the crown width of trees (as intermediary step to obtain the crown ratio).

### Metereological input

Weather input data must include variables calculated at the **daily** scale. The variables required by function `growth()` depend on the transpiration mode, similarly to function `spwb()`. We recommend meteorological input to be generated using package **meteoland** [@DeCaceres2018].

## Model output