# (PART) Static modules {-}


# Allometric models {#allometricmodels}

The purpose of this chapter is to describe how certain plant structural attributes are estimated in **medfate** using allometric relationships. These static models are used to initialize vegetation input parameters from forest plot data before simulations (in functions `forest2spwbInput()` and `forest2growthInput()`), to update vegetation structure during growth simulations or to calculate foliar biomass for fuel assessments. 

## Input data

### Forest plot data

As explained in section \@ref(vegetationinput), **medfate** has been specially designed to work with forest inventory plots with data in form of plant cohorts. The tree/shrub cohort attributes required to apply allometric models are the following:

| Symbol | Units | R  | Description                        | trees | shrubs |
|--------|-------|----| ------------------------------------|-----|-----|
| $SP_i$  |  | `Species` | Species identity |  Y  |  Y  |
| $H_i$  | $cm$  | `Height` | Average tree or shrub height |  Y  |  Y  |
| $N_i$ | $ind · ha^{-1}$ | `N` | Density of tree individuals | Y | N |
| $DBH_i$ | $cm$ | `DBH` | Tree diameter at breast height | Y | N |
| $Cover_i$ | % | `Cover` | Shrub percent cover | N | Y |

Most allometric functions require data in form of a `forest` object (see section \@ref(forestobjects)).

### Species parameters

The following table shows the allometric coefficients needed for the calculations detailed in this chapter.

| Symbol       | Units | R param       | Description                      |
|--------------|-------|---------------|----------------------------------|
| $a_{fbt}$, $b_{fbt}$, $c_{fbt}$, $d_{fbt}$ | | `a_fbt`, `b_fbt`, `c_fbt`, `d_fbt` | Coefficients to calculate foliar biomass of an individual tree  |
| $a_{ash}$ | | `a_ash` | Coefficient relating the square of shrub height with shrub area |
| $a_{bsh}$, $b_{bsh}$ | | `a_bsh`, `b_bsh` | Coefficients relating crown volume with dry weight of shrub individuals |
| $a_{cr}$, $b_{1cr}$, $b_{2cr}$, $b_{3cr}$, $c_{1cr}$, $c_{2cr}$ | | `a_cr`, `b_1cr`, `b_2cr`, `b_3cr`, `c_1cr`, `c_2cr` | Coefficients to calculate crown ratio of trees |
| $cr$ | [0-1] | `cr` | Ratio between crown length and total height for shrubs |
| $r_{6.35}$ | | `r635` | Ratio between the weight of leaves plus branches and the weight of leaves alone for branches of 6.35 mm |
| $SLA$  | $m^2 \cdot kg^{-1}$ | `SLA` | Specific leaf area |

## Allometric relationships

### Leaf biomass 

Leaf biomass calculations are done differently for trees and shrub cohorts. They are calculated from `forest` objects using function `plant_foliarBiomass()`.

**Tree cohorts**

Foliar biomass for a single tree of cohort $i$ ($FB_{tree,i}$; in $kg$) is calculated using:
\begin{equation}
FB_{tree,i} = a_{fbt} \cdot DBH_{i}^{b_{fbt}}\cdot e^{c_{fbt}\cdot BAL_i} \cdot DBH_{i}^{d_{fbt} \cdot BA_{sup}}
(\#eq:onetreefoliarbiomass)
\end{equation}
where $DBH_{i}$ is the diameter of the tree (in $cm$), $BAL_i$ is the cummulative basal area ($m^2\cdot ha^{-1}$) of trees having a larger diameter, and $a_{fbt}$, $b_{fbt}$, $c_{fbt}$ and $c_{fbt}$ are species-specific regression coefficients. The foliar biomass of the whole tree cohort ($FB_{i}$; in $kg\cdot m^{-2}$) is obtained multiplying tree foliar biomass by tree density  ($N_{i}$; in $ind.\cdot ha^{-1}$):
\begin{equation}
FB_{i} = FB_{tree,i}\cdot (N_{i}/10000)
(\#eq:treefoliarbiomass)
\end{equation}

**Shrub cohorts**

To calculate the leaf biomass of a shrub cohort, we first determine $A_{sh,i}$, the area (in $cm^2$) occupied by one average individual of height $H_{i}$ (in $cm$), using the quadratic relationship: 
\begin{equation}
A_{sh,i} = a_{ash} \cdot H_{i}^2
\end{equation}
where $a_{ash}$ is a species-specific parameter. The model then estimates the dry weight of leaves and branches up to 6.35mm in diameter ($B_{sh,i}$, in kg) of this average individual (i.e. fine fuel biomass), using an allometric relationship with shrub crown phytovolume assuming a cylinder (in $cm^3$):
\begin{equation}
B_{sh,i} = a_{bsh} \cdot (A_{sh,i}\cdot H_{i}\cdot cr_i)^{b_{bsh}}
\end{equation}
where $a_{bsh}$ and $b_{bsh}$ are species-specific parameters and $cr_i$ is the crown ratio (a value between 0 and 1, the ratio between crown length and total height). Shrub density ($N_{i}$; in $ind.\cdot m^{-2}$) can be grossly estimated from percent cover ($C_{i}$, in percent) and $A_{sh,i}$ (in $cm^{-2}$):
\begin{equation}
N_{i} = \frac{C_{i}/100}{A_{sh,i}/10000}
\end{equation}
The fine fuel biomass of a shrub cohort ($W_{i}$, in $kg \cdot m^{-2}$) is simply the product of $B_{sh,i}$ ($kg$ of dry weight) and $N_{i}$:
\begin{equation}
W_{i} =  B_{sh,i} \cdot N_{i}
(\#eq:shrubloading)
\end{equation}
Foliar biomass (in $kg \cdot m^{-2}$) can be obtained using the species-specific ratio $r_{6.35,i}$:
\begin{equation}
FB_{i} =  W_{i}/r_{6.35, i}
(\#eq:shrubfoliarbiomass)
\end{equation}
If not known, $r_{6.35,i}$ can be set to a default value of 2 (equivalent to 50% of weight corresponding to leaves).


### Leaf area and LAI
Leaf area index ($LAI$ in $m^2 \cdot m^{-2}$) of a given cohort $i$ can be calculated from its foliar biomass (in $kg \cdot m^{-2}$) by using a *specific leaf area* coefficient ($SLA$, in $m^2 \cdot kg^{-1}$) that in **medfate** is species-specific:
\begin{equation}
LAI_{i} =  FB_{i} \cdot SLA
\end{equation}
The leaf area ($LA$ in $m^2$) of an individual of the cohort is found by dividing it by plant density ($N_i$, in $ind.\cdot ha^{-1}$) and multiplying by 10000 $m^2 \cdot ha^{-1}$:
\begin{equation}
LA_{i} =  10000 \cdot LAI_{i} / N_{i}
\end{equation}

LAI values are calculated from `forest` objects using function `plant_LAI()`.

### Crown vertical dimensions {#crownbaseheight}


Crown base height, i.e. the height were the first living branch of trees or shrubs occurs, is an important parameter to know the vertical distribution of leaves (see section \@ref(leafdistribution)). Crown base height of a plant cohort $i$ (i.e., $H_{crown,i}$, in $cm$) is related to the total height of the cohort ($H_i$, in $cm$) and its crown ratio ($CR_i$), which is the ratio between crown length and plant height:
\begin{equation}
H_{crown,i} = (1 - CR_i) \cdot H_i
(\#eq:CrownHeight)
\end{equation}
In the case of shrubs the crown ratio $CR_i$ is normally an input (species-specific) parameter ($cr$). In the case of trees, the crown ratio is modelled as a function of tree size and stand competition, following a modification of the logistic equation of @Hasenauer1996 :
\begin{equation}
CR_i = \frac{1}{1+e^{-(a_{cr}+b_{1cr}\cdot HD_i +b_{2cr} \cdot (H_i/100)+b_{3cr} \cdot DBH_i^2+c_{1cr} \cdot BAL_i + c_{2cr} \cdot ln(CCF_i))}}
(\#eq:treecrownratio)
\end{equation}
where $HD_i = H_i/(100\cdot DBH_i)$ is the height to diameter ratio (in $m\cdot cm^{-1}$), $H_i$ is the tree height, $DBH_i$ is the diameter, $CCF_i$ is the crown competition factor and $a_{cr}$, $b_{1cr}$, $b_{2cr}$, $b_{3cr}$, $c_{1cr}$ and $c_{2cr}$ are species-specific parameters. The crown competition factor is in turn calculated using [@Krajicek1961]:
\begin{equation}
CCF_i = \sum_{i}{N_i \cdot \pi \cdot (CW_i/2)^2/100}
\end{equation}
where $N_i$ is the tree density and $CW_i$ is the crown width (in $m$) assuming an open-grown tree, estimated from an allometric relationship with tree diameter:
\begin{equation}
CW_i = a_{cw}\cdot DBH_i^{b_{cw}} 
\end{equation}
where again $a_{cw}$ and $b_{cw}$ are species-specific parameters. 

Crown ratios can be calculated from forest objects using function `plant_crownRatio()`. Similar calculations are performed to estimate crown length and crown base height, with functions `plant_crownLength()` and `plant_crownBaseHeight()`, respectively.