
# Symbols

The following tables list all symbols used in this document, along with their units and definition. When symbols are input for **medfate** model functions, the R name of those parameters in the package (either in data frame `SpParamsMED`, soil input data frame, or the output of functions such as `spwbInput()`) is also indicated. 

## Soils

| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $d_{s}$ | $mm$ | `widths` | Soil layer width in soil layer $s$ |
| $P_{clay,s}$ | % | `clay`|  Percent of clay in soil layer $s$ |
| $P_{sand,s}$ | % | `sand` | Percent of sand in soil layer $s$ |
| $OM$ | % | `om` | Percentage of organic mater per dry weight |
| $BD_{s}$ | $g\cdot cm^{-3}$ | `bd` | Bulk density in soil layer $s$ |
| $P_{rocks,s}$ | % | `rfc` | Percentage of rock fragment content in soil layer $s$ |
| $\theta_s$ | $m^3 \cdot m^{-3}$ | | Volumetric moisture in soil layer $s$ |
| $\Psi_s$ | MPa | | Water potential in soil layer $s$ |
| $\Psi_{fc}$ | MPa | | Water potential at field capacity |
| $A$, $B$ | | | Parameters of the Saxton pedotransfer functions |
| $\theta_{sat}$ |$m^3 \cdot m^{-3}$ | `VG_theta_sat`| Volumetric moisture at saturation |
| $\theta_{fc}$ |$m^3 \cdot m^{-3}$ |  | Volumetric moisture at field capacity (-0.033 MPa) |
| $\theta_{wp}$ |$m^3 \cdot m^{-3}$ |  | Volumetric moisture at wilting point (-1.5 MPa) |
| $\theta_{res}$ |$m^3 \cdot m^{-3}$ | `VG_theta_res` | Residual volumetric moisture |
| $n$ | | `VG_n` | Parameter of the Van Genuchten [-@Genuchten1980] model |
| $\alpha$ | | `VG_alpha`| Parameter of the Van Genuchten [-@Genuchten1980] model |
| $P_{macro, s}$ | % | `macro` | Percentage of macroporosity corresponding to each soil layers. |
| $\gamma_{soil}$ | $mm \cdot day^{-1}$ | `Gsoil` | The maximum daily evaporation from soil |
| $\kappa_{soil}$ | | `Ksoil` | Extinction parameter to regulate the amount of water evaporated from each soil layer |
| $WT$ | $mm$ | | Water table depth |
| $V_{s}$ | $mm$ | | Water content in soil layer $s$ |
| $V_{fc, soil}$ | $mm$ | | Water retention capacity of the whole soil |
| $W_{s}$ | [0-1] |`W` | Proportion of volumetric moisture in relation to field capacity in soil layer $s$ |
| $S_{snow}$ | $mm$ |`SWE` | Snow water equivalent of the snow pack storage over the soil surface |


## Vegetation

| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $SP_i$  |  | `Species` | Species identity of cohort $i$ |
| $A_{sh,i}$  | $cm^2$ |  | Area occupied by an average shrub individual of cohort $i$ |
| $B_{sh,i}$  | $kg$ |  | Fine-fuel biomass of an average shrub individual of cohort $i$ |
| $H_i$  | $cm$  | `Height` | Average tree or shrub height of cohort $i$ |
| $H_{crown,i}$ | $cm$ | | Crown base height (i.e. the height corresponding to the first living branch) of cohort $i$ |
| $CCF_i$ | | | Crown competition factor of cohort $i$ |
| $CW_i$ | $m$ | | Crown width that a tree of cohort $i$ would have in open-ground conditions |
| $CR_i$ |       | `CR`| Crown ratio (i.e. ratio between crown length and plant height) of cohort $i$ |
| $N_i$ | $ind · ha^{-1}$ | `N` | Density of tree individuals of cohort $i$ |
| $DBH_i$ | $cm$ | `DBH` | Diameter at breast height of trees in cohort $i$ |
| $Cover_i$ | % | `Cover` | Percent cover of shrubs in cohort $i$ |
| $FB_{i}$ | $kg \cdot m^{-2}$ | | Foliar biomass of cohort $i$ |
| $FB_{tree,i}$ | $kg$ | | Foliar biomass of a single tree of cohort $i$ |
| $\phi_i$ | [0-1] | | Fraction of maximum leaf area currently expanded for cohort $i$ |
| $LAI^{live}_i$ | $m^2 \cdot m^{-2}$ | `LAI_live` | (Maximum) leaf area index (one-side leaf area per surface area of the stand) of cohort $i$ |
| $LAI^{dead}_i$ | $m^2 \cdot m^{-2}$ | `LAI_dead` | Dead leaf area index (one-side dead leaf area per surface area of the stand) of cohort $i$ |
| $LAI^{\phi}_i$ | $m^2 \cdot m^{-2}$ | `LAI_expanded` | Current expanded leaf area index (one-side expanded leaf area per surface area of the stand) of cohort $i$ |
| $LAI^{all}_{i}$ | $m^2 \cdot m^{-2}$ | | Total leaf area index (live or dead) of cohort $i$ |
| $LAI^{live}_{stand}$ | $m^2 \cdot m^{-2}$ | | Maximum leaf area index of living leaves of the stand |
| $LAI^{dead}_{stand}$ | $m^2 \cdot m^{-2}$ | | Leaf area index of dead leaves of the stand |
| $LAI^{\phi}_{stand}$ | $m^2 \cdot m^{-2}$ | | Current expanded leaf area index of live leaves of the stand |
| $LAI_{stand}$ | $m^2 \cdot m^{-2}$ | | Total leaf area index (live or dead) of the stand |
| $LA_{i}$ | $m^{2}$ | | Leaf area of an individual of cohort $i$ |
| $v_{i,s}$ | [0-1] | `V[i,s]` | The proportion of fine roots of cohort $i$ in soil layer $s$ |
| $W_{i}$ | $kg \cdot m^{-2}$ | | Fine fuel biomass of cohort $i$ |
| $Z_{50,i}$ | mm | `Z50` | Depth above which 50% of the fine root mass of cohort $i$ is located |
| $Z_{95,i}$ | mm | `Z95` | Depth above which 95% of the fine root mass of cohort $i$ is located |


## Meteorology


| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $T_{mean}$ | $^{\circ} \mathrm{C}$ | `MeanTemperature` | Mean temperature |
| $T_{min}$ | $^{\circ} \mathrm{C}$ | `MinTemperature` | Minimum temperature |
| $T_{max}$ | $^{\circ} \mathrm{C}$ | `MaxTemperature` | Maximum temperature |
| $RH_{min}$ | % | `MinRelativeHumidity` | Minimum relative humidity |
| $RH_{max}$ | % | `MaxRelativeHumidity` | Maximum relative humidity |
| $P$ | $L \cdot m^{-2} = mm$ | `Precipitation` | Precipitation |
| $PET$ | $L \cdot m^{-2} = mm$ | `PET` | Potential evapotranspiration, preferably calculated using Penman's equation |
| $Rad$ | $MJ \cdot m^{-2}$ | `Radiation` | Solar radiation after accounting for clouds |
| $u$ | $m \cdot s^{-1}$ | `WindSpeed` | Wind speed |
| $GDD$ | $^{\circ} \mathrm{C}$ | `GDD` | Growth degree days. |

## Anatomy 

| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $HV$  | $m^2 \cdot m^{-2}$ | `1/Al2As` | Huber value (ratio of sapwood area to leaf area) |
|  $LW$   | $cm$  | `LeafWidth` | Leaf width |
| $SLA$  | $m^2 \cdot kg^{-1}$ | `SLA` | Specific leaf area |
| $\rho_{leaf}$ | $g \cdot cm^{-3}$ | `LeafDensity` | Leaf tissue density |
| $\rho_{wood}$ | $g \cdot cm^{-3}$ | `WoodDensity` | Wood tissue density |
| $\Theta_{sapwood}$ | $m^3 \cdot m^{-3}$ | | Sapwood porosity (volume of empty spaces over total volume) |
| $\Theta_{leaf}$ | $m^3 \cdot m^{-3}$ | | Leaf porosity (volume of empty spaces over total volume) |

## Light extinction

| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $k_{PAR,i}$ | | `k` | PAR extinction coefficient for cohort $i$ |
| $k_{SWR,i}$ | |  | SWR extinction coefficient for cohort $i$ |
| $L^{PAR}_{ground}$ | [0-1] | `LgroundPAR` | Fraction of PAR reaching the ground |
| $L^{SWR}_{ground}$ | [0-1] | `LgroundSWR` | Fraction of SWR reaching the ground |


## Hydrology and water balance

| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $Ps$ | $mm$ | `Snow`| Precipitation as snow |
| $Pr$ | $mm$ | `Rain`| Precipitation as rainfall |
| $Sm$ | $mm$ | `Snowmelt` | Snowmelt |
| $Pr_{net}$ | $mm$ | `NetRain`| Net rainfall |
| $In$ | $mm$ | `Interception` | Interception loss |
| $Ru$ | $mm$ | `Runoff` | Water exported from the stand as runoff |
| $Ro$ | $mm$ | `Runon` | Water imported to the stand as runon |
| $Dd$ | $mm$ | `DeepDrainage` | Water exported from the stand as deep drainage |
| $P_G$ | $mm$ | | Amount of rainfall needed to saturate the canopy for a given event |
| $S_{canopy}$ | $mm$ | `Cm` | Canopy water storage capacity |
| $(E/R)$ | |  | Ratio between evaporation rate and rainfall rate |  
| $C_{canopy}$ | [0-1] | | Canopy cover | 
| $PE_{soil}$ | $mm$ | | Evaporation demand from the soil |
| $SE_{soil}$ | $mm$ | | Evaporation supply from the soil |
| $Es$ | $mm$ | `SoilEvaporation` | Evaporation from the soil surface |

## Energy balance

| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $K_{abs,ca}$ | $W$ | `SWRcanin` |  Atmosphere shortwave radiation absorbed by the canopy |
| $K_{abs,sa}$ | $W$ | `SWRsoilin`  |  Atmosphere shortwave radiation absorbed by the soil |
| $L_{abs,ca}$ | $W$ | `LWRcanin`  |  Atmosphere longwave radiation absorbed by the canopy |
| $L_{abs,sa}$ | $W$ | `LWRsoilin` |  Atmosphere longwave radiation absorbed by the soil |
| $L_{abs,cs}$ | $W$ | `LWRsoilcan`|  Longwave radiation emmited by the soil and absorbed by the canopy |
| $L_{em,c}$ | $W$ | `LWRcanout` |  Longwave radiation emmited by the canopy |
| $L_{em,s}$ | $W$ | `LWRsoilout`|  Longwave radiation emmited by the soil |
| $H_{ca}$ | $W$ | `Hcan` |  Convective heat exchange between the canopy and the atmosphere |
| $H_{cs}$ | $W$ | `Hcansoil` |  Convective heat exchange between the canopy and the soil |
| $LE_{c}$ | $W$ | `LEcan`| Energy released as latent heat from the canopy towards the atmosphere |
| $LE_{s}$ | $W$ | `LEsoil` | Energy released as latent heat from the soil towards the atmosphere |
| $T_{c}$ | $^\circ \mathrm{C}$ | | Canopy temperature |
| $T_{s}$ | $^\circ \mathrm{C}$ | | Soil temperature |
| $C_{c}$ | $J \cdot m^{-3} \cdot K^{-1}$ | | Canopy thermal capacity (revise units) |
| $C_{s}$ | $J \cdot m^{-3} \cdot K^{-1}$ | | Soil thermal capacity |

## Plant hydraulics

| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $K_{stem,max,ref}$ | $kg \cdot s^{-1} \cdot m^{-1} \cdot MPa^{-1}$ | `Kmax_stemxylem` | Maximum stem sapwood reference conductivity per leaf area unit |
| $K_{root,max,ref}$ | $kg \cdot s^{-1} \cdot m^{-1} \cdot MPa^{-1}$ | `Kmax_rootxylem` | Maximum root sapwood reference conductivity per leaf area unit |
| $k_{stem, \max}$ | $mmol \cdot s^{-1} \cdot m^{-2} \cdot MPa^{-1}$ |  `VCstem_kmax` | Maximum whole-stem conductance (per leaf area unit) |
| $k_{root, \max}$ | $mmol \cdot s^{-1} \cdot m^{-2} \cdot MPa^{-1}$ |  `VCroot_kmax` | Maximum root conductance (per leaf area unit) |
| $k_{rhizo, \max}$ | $mmol \cdot s^{-1} \cdot m^{-2} \cdot MPa^{-1}$ |  | Maximum rhizosphere conductance (per leaf area unit) |
| $k_{leaf, \max}$ | $mmol \cdot s^{-1} \cdot m^{-2} \cdot MPa^{-1}$ | `VCleaf_kmax` | Maximum leaf conductance (per leaf area unit) |
| $c_{leaf}$, $d_{leaf}$ | (unitless), MPa | `VCleaf_c`, `VCleaf_d` | Parameters of the vulnerability curve for leaves |
| $c_{root}$, $d_{root}$ | (unitless), MPa | `VCroot_c`, `VCroot_d` | Parameters of the vulnerability curve for root xylem |
| $c_{stem}$, $d_{stem}$ | (unitless), MPa | `VCstem_c`, `VCstem_d` | Parameters of the vulnerability curve for stem xylem |
| $n$, $\alpha$ | | | Texture-specific parameters of the van Genuchten equation |
| $\Psi$ | MPa | | Water potential in a given water compartment |
| $\Psi_P$ | MPa | | Turgor water potential in a given water compartment |
| $\Psi_S$ | MPa | | Osmotic (solute) water potential in a given water compartment |
| $\Psi_{cav}$ | MPa | | Minimum water potential experienced by xylem in previous steps (cavitation) |
| $\Psi_{canopy}$ | MPa | | Canopy water potential |
| $\Psi_{leaf}$ | MPa | | Leaf water potential |
| $\Psi_{rootcrown}$ | MPa | | Water potential at the root crown |
| $\Psi_{stem}$ | MPa | | Water potential at the end (highest part) of the stem |
| $PLC$ | [0-1] | | Proportion of conductance loss in stem xylem tissue |
| $p_{root}$ | [0-1] | `pRootDisc` | Relative root conductance leading to hydraulic disconnection from a soil layer |



## Plant water compartments
| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $\epsilon_{leaf}$ | MPa | `LeafEPS` | Modulus of elasticity of leaves |
| $\epsilon_{stem}$ | MPa | `StemEPS` | Modulus of elasticity of symplastic xylem tissue |
| $\pi_{0,leaf}$ | MPa | `LeafPI0` | Osmotic potential at full turgor of leaves |
| $\pi_{0,stem}$ | MPa | `StemPI0` | Osmotic potential at full turgor of symplastic xylem tissue |
| $RWC$ | [0-1] | | Relative water content |
| $RWC_{sym}$ | [0-1] | | Relative water content in the symplasm fraction of a tissue |
| $RWC_{apo}$ | [0-1] | | Relative water content in the apoplasm fraction of a tissue |
| $V_{segment}$ | $m^3 \cdot m^{-2}$ | | Water capacity of a segment (leaf or stem) |
| $V_{leaf}$ | $m^3 \cdot m^{-2}$ | `Vleaf` | Leaf water capacity per leaf area unit |
| $V_{sapwood}$ | $m^3 \cdot m^{-2}$ | `Vsapwood` | Sapwood water capacity per leaf area unit |

## Stomatal regulation and photosynthesis
| Symbol | Units | R param | Description                        |
|--------|-------|---------|------------------------------------|
| $g_{swmin}$ | $mol H_2O \cdot s^{-1} \cdot m^{-2}$ | `Gwmin` | Minimum stomatal conductance to water vapour |
| $g_{swmax}$ | $mol H_2O \cdot s^{-1} \cdot m^{-2}$ | `Gwmax` | Maximum stomatal conductance to water vapour |
| $J_{max, 298}$ | $\mu mol electrons \cdot m^{-2} \cdot s^{-1}$ | `Jmax298` | Maximum rate of electron transport at 298K |
| $V_{max, 298}$ | $\mu mol CO_2 \cdot s^{-1} \cdot m^{-2}$ | `Vmax298` | Rubisco's maximum carboxylation rate at 298K |
