
### Leaf water potential

```{r}
df_eval<-NULL
cohNamesOut <- character()
sitesOut <- character()
modesOut <- character()
wpOut <- character()
for(i in 1:nrow(df_site)) {
  if(df_site$Mode[[i]] !="granier") {
      cohNames <- row.names(df_site$InputObject[[i]]$cohorts)
      for(j in 1:length(cohNames)) {
        measured_var <- paste0("MD_", cohNames[j])
        if(measured_var %in% names(df_site$SiteData[[i]]$measuredData)) {
          v<-medfate::evaluation_stats(df_site$Result[[i]], df_site$SiteData[[i]]$measuredData,
                                       type= "WP", cohort = cohNames[j])
          if(v[["n"]][1]>0) {
            if(is.null(df_eval)) {
              df_eval <- v
            } else {
              df_eval <- rbind(df_eval, v)
            }
            wpOut <- c(wpOut, c("Predawn", "Midday"))
            cohNamesOut <-c(cohNamesOut, rep(cohNames[j],2))
            sitesOut<- c(sitesOut, rep(df$Site[i],2))
            modesOut<- c(modesOut, rep(df$Mode[i],2))
          }
        }
      }
  }
}
if(!is.null(df_eval)) {
  df_all <- data.frame(Site = sitesOut, Mode = modesOut, Cohort = cohNamesOut, WP = wpOut, df_eval)
}
row.names(df_all)<- NULL
df_all|>
  kbl() |>
  kable_styling()
```


```{r, fig.height=3, fig.width=9, fig.align="center"}
cohNames <- row.names(df_site$InputObject[[1]]$cohorts)
spNames <- df_site$InputObject[[1]]$cohorts$Name
for(j in 1:length(cohNames)) {
  measured_var <- paste0("PD_", cohNames[j])
  to_plot <- measured_var %in% names(df_site$SiteData[[2]]$measuredData)
  if(to_plot) {
    to_plot <- to_plot && any(!is.na(df_site$SiteData[[2]]$measuredData[[measured_var]]))
  }
  if(to_plot) {
    pb<-medfate::evaluation_plot(df_site$Result[[2]], df_site$SiteData[[2]]$measuredData, type= "WP", 
                                 plotType = "scatter", cohort = cohNames[j])+labs(subtitle="Sperry")
    pc<-medfate::evaluation_plot(df_site$Result[[3]], df_site$SiteData[[3]]$measuredData, type= "WP", 
                                 plotType = "scatter", cohort = cohNames[j])+labs(subtitle="Cochard", title="")
    l <- cowplot::get_legend(pb)
    p1 <- cowplot::plot_grid(pb + theme(legend.position = "none"),
                             pc + theme(legend.position = "none"), 
                             l, 
                             ncol = 3)
    print(p1)
    eval_table_sperry <- medfate::evaluation_table(df_site$Result[[2]], df_site$SiteData[[2]]$measuredData,
                                                   type= "WP",cohort = cohNames[j])
    eval_table_cochard <- medfate::evaluation_table(df_site$Result[[3]], df_site$SiteData[[3]]$measuredData,
                                                    type= "WP", cohort = cohNames[j])
    obs_table <- eval_table_sperry[(!is.na(eval_table_sperry$PD_obs)) | (!is.na(eval_table_sperry$MD_obs)) ,]
    p2 <- ggplot()+
      geom_ribbon(aes(x = Dates, ymin = PD_mod, ymax = MD_mod), data = eval_table_sperry, alpha = 0.5, fill = "green")+
      geom_ribbon(aes(x = Dates, ymin = PD_mod, ymax = MD_mod), data = eval_table_cochard, alpha = 0.5, fill = "blue")+
      geom_point(aes(x = Dates, y = PD_obs), data = obs_table)+
      geom_point(aes(x = Dates, y = MD_obs), data = obs_table)+
      geom_segment(aes(x = Dates, xend = Dates, y = MD_obs, yend= PD_obs), data = obs_table)+
      theme_bw()+ ylab("Leaf water potential (MPa)")+ xlab("")
    print(p2)
  }
}
```