# `r site_name`

```{r, echo = FALSE}
df_site <- df[df$Site==site_name,]
```

## Soil moisture
```{r}
df_eval <-NULL
for(i in 1:nrow(df_site)) {
  eval_REW <- "SWC" %in% names(df_site$SiteData[[i]]$measuredData)
  if(eval_REW) {
    v<-medfate::evaluation_stats(df_site$Result[[i]], df_site$SiteData[[i]]$measuredData, type= "REW")
    if(is.null(df_site)) df_eval <- v
    else df_eval <- cbind(df_eval, v)
  }
}
if(!is.null(df_eval)) {
  df_all <- cbind(df_site[,c("Site", "Mode")], as.data.frame(t(df_eval)))
  knitr::kable(df_all, row.names = FALSE)
}
```

```{r, fig.height=4, fig.width=9, fig.align="center"}
eval_table_granier <- medfate::evaluation_table(df_site$Result[[1]], df_site$SiteData[[1]]$measuredData, type= "REW")
eval_table_sperry <- medfate::evaluation_table(df_site$Result[[2]], df_site$SiteData[[2]]$measuredData, type= "REW")
eval_table_cochard <- medfate::evaluation_table(df_site$Result[[3]], df_site$SiteData[[3]]$measuredData, type= "REW")
eval_all <- eval_table_granier[,c(1,2)]
eval_all$Granier <- eval_table_granier$Modelled
eval_all$Sperry <- eval_table_sperry$Modelled
eval_all$Cochard <- eval_table_cochard$Modelled
eval_all_long <- eval_all |>
  tidyr::pivot_longer(cols = 2:5, names_to = "Mode", values_to="REW") |>
  dplyr::mutate(Mode = factor(Mode, levels = c("Observed", "Granier", "Sperry", "Cochard")))
p1<-ggplot(eval_all_long, mapping = aes(x=Dates, y=REW))+
  geom_line(mapping=aes(col = Mode, alpha = Mode))+
  scale_alpha_manual("", values=c(1.0,0.5,0.5,0.5))+
  scale_color_manual("",values = c("black", "red", "green", "blue"))+
  # scale_linetype_manual("", values = c("solid", "dashed", "dashed", "dashed"))+
  xlab("")+
  theme_bw()
p2<-ggplot(eval_all, mapping = aes(x=Observed))+
  geom_point(mapping=aes(y = Granier), col = "red", size =0.5, alpha =0.5)+
  geom_point(mapping=aes(y = Sperry), col = "green", size =0.5, alpha =0.5)+
  geom_point(mapping=aes(y = Cochard), col = "blue", size =0.5, alpha =0.5)+
  geom_abline(slope = 1, intercept = 0, size = 1.5)+
  xlab("Observed")+ ylab("Predicted")+
  theme_bw()
cowplot::plot_grid(p2, p1, ncol=2, rel_widths = c(0.7,1))
```

## Plant transpiration

```{r}
df_eval<-NULL
cohNamesOut <- character()
sitesOut <- character()
modesOut <- character()
for(i in 1:nrow(df_site)) {
  cohNames <- row.names(df_site$InputObject[[i]]$cohorts)
  for(j in 1:length(cohNames)) {
    measured_var <- paste0("E_", cohNames[j])
    if(measured_var %in% names(df_site$SiteData[[i]]$measuredData)) {
      v<-medfate::evaluation_stats(df_site$Result[[i]], df_site$SiteData[[i]]$measuredData,
                                   type= "E", cohort = cohNames[j])
      if(v[["n"]]>0) {
        if(is.null(df_eval)) {
          df_eval <- v
        } else {
          df_eval <- cbind(df_eval, v)
        }
        cohNamesOut <-c(cohNamesOut, cohNames[j])
        sitesOut<- c(sitesOut, df_site$Site[i])
        modesOut<- c(modesOut, df_site$Mode[i])
      }
    }
  }
}
if(!is.null(df_eval)) {
  df_all <- data.frame(Site = sitesOut, Mode = modesOut, Cohort = cohNamesOut, t(df_eval))
  knitr::kable(df_all, row.names = FALSE)
}
```


```{r, fig.height=4, fig.width=9, fig.align="center"}
cohNames <- row.names(df_site$InputObject[[1]]$cohorts)
spNames <- df_site$InputObject[[1]]$cohorts$Name
for(i in 1:length(cohNames)) {
  measured_var <- paste0("E_", cohNames[i])
  to_plot <- measured_var %in% names(df_site$SiteData[[1]]$measuredData)
  if(to_plot) {
    to_plot <- to_plot && any(!is.na(df_site$SiteData[[1]]$measuredData[[measured_var]]))
  }
  if(to_plot) {
    eval_table_granier <- medfate::evaluation_table(df_site$Result[[1]], df_site$SiteData[[1]]$measuredData, 
                                                    type= "E", cohort = cohNames[i])
    eval_table_sperry <- medfate::evaluation_table(df_site$Result[[2]], df_site$SiteData[[2]]$measuredData, 
                                                   type= "E",cohort = cohNames[i])
    eval_table_cochard <- medfate::evaluation_table(df_site$Result[[3]], df_site$SiteData[[3]]$measuredData, 
                                                    type= "E", cohort = cohNames[i])
    eval_all <- eval_table_granier[,c(1,2)]
    eval_all$Granier <- eval_table_granier$Modelled
    eval_all$Sperry <- eval_table_sperry$Modelled
    eval_all$Cochard <- eval_table_cochard$Modelled
    eval_all_long <- eval_all |>
      tidyr::pivot_longer(cols = 2:5, names_to = "Mode", values_to="E") |>
      dplyr::mutate(Mode = factor(Mode, levels = c("Observed", "Granier", "Sperry", "Cochard")))
    p1<-ggplot(eval_all_long, mapping = aes(x=Dates, y=E))+
      geom_line(mapping=aes(col = Mode, alpha = Mode))+
      scale_alpha_manual("", values=c(1.0,0.5,0.5,0.5))+
      scale_color_manual("",values = c("black", "red", "green", "blue"))+
      xlab("")+ylab("Transpiration per leaf area (l/m2)") + labs(title="")+
      theme_bw()
    p2<-ggplot(eval_all, mapping = aes(x=Observed))+
      geom_point(mapping=aes(y = Granier), col = "red", size =0.5, alpha =0.5)+
      geom_point(mapping=aes(y = Sperry), col = "green", size =0.5, alpha =0.5)+
      geom_point(mapping=aes(y = Cochard), col = "blue", size =0.5, alpha =0.5)+
      geom_abline(slope = 1, intercept = 0, size = 1.5)+
      xlab("Observed")+ ylab("Predicted")+ labs(title = paste0(cohNames[i], " (", spNames[i],")"))+
      theme_bw()
    print(cowplot::plot_grid(p2, p1, ncol=2, rel_widths = c(0.7,1)))
  }
}
```

## Water potentials

```{r}
df_eval<-NULL
cohNamesOut <- character()
sitesOut <- character()
modesOut <- character()
wpOut <- character()
for(i in 1:nrow(df_site)) {
  if(df_site$Mode[[i]] !="granier") {
      cohNames <- row.names(df_site$InputObject[[i]]$cohorts)
      for(j in 1:length(cohNames)) {
        measured_var <- paste0("MD_", cohNames[j])
        if(measured_var %in% names(df_site$SiteData[[i]]$measuredData)) {
          v<-medfate::evaluation_stats(df_site$Result[[i]], df_site$SiteData[[i]]$measuredData,
                                       type= "WP", cohort = cohNames[j])
          if(v[["n"]][1]>0) {
            if(is.null(df_eval)) {
              df_eval <- v
            } else {
              df_eval <- rbind(df_eval, v)
            }
            wpOut <- c(wpOut, c("Predawn", "Midday"))
            cohNamesOut <-c(cohNamesOut, rep(cohNames[j],2))
            sitesOut<- c(sitesOut, rep(df$Site[i],2))
            modesOut<- c(modesOut, rep(df$Mode[i],2))
          }
        }
      }
  }
}
if(!is.null(df_eval)) {
  df_all <- data.frame(Site = sitesOut, Mode = modesOut, Cohort = cohNamesOut, WP = wpOut, df_eval)
  knitr::kable(df_all, row.names = FALSE)
}
```

