# `r site_name`


## General information

```{r}
as.data.frame(df_site$SiteData[[1]]$siteData)|> 
  kbl() |>
  kable_styling()
```

## Model inputs
### Vegetation 

```{r}
df_trees <- as.data.frame(df_site$SiteData[[1]]$treeData)
df_shrubs <- as.data.frame(df_site$SiteData[[1]]$shrubData)
miscData <- df_site$SiteData[[1]]$miscData
if(nrow(df_trees)>0 && nrow(df_shrubs)>0) {
  df <- df_trees |>
    dplyr::full_join(df_shrubs)
} else if(nrow(df_trees)>0) {
  df <- df_trees
} else {
  df <- df_shrubs
}
if(miscData$herbCover>0) {
  df_herbs <- data.frame(Species = "Herbaceous layer", Cover = miscData$herbCover, Height = miscData$herbHeight)
  df <- df |>
    dplyr::full_join(df_herbs)
}
df |> 
  kbl() |>
  kable_styling()
```


### Soil

```{r}
as.data.frame(df_site$SiteData[[1]]$soilData)|> 
  kbl() |>
  kable_styling()
```

### Custom traits

```{r, max.print=5}
custom_df <- df_site$SiteData[[1]]$customParams
custom_df <- custom_df[,colSums(is.na(custom_df))< nrow(custom_df), drop = FALSE]
custom_df |> 
  kbl() |>
  kable_styling()
```

### Custom control

```{r, max.print=5}
df_site$SiteData[[1]]$customControl |> 
  as.data.frame() |>
  kbl() |>
  kable_styling()
```

### Remarks

```{r, max.print=5}
as.data.frame(df_site$SiteData[[1]]$remarks)|> 
  kbl() |>
  kable_styling()
```

## Macroclimate
```{r, fig.height=2, fig.width=8, fig.align="center"}
plot(df_site$Result[[1]], "PET_Precipitation")
```

## Microclimate
```{r, fig.height=4, fig.width=8, fig.align="center"}
cowplot::plot_grid(plot(df_site$Result[[2]], "TemperatureRange")+labs(title="Sperry"),
                   plot(df_site$Result[[3]], type = "TemperatureRange")+labs(title="Sureau"),
                   nrow=2)
```

## Runoff & deep drainage
```{r, fig.height=6, fig.width=8, fig.align="center"}
cowplot::plot_grid(plot(df_site$Result[[1]], "Export")+labs(title="Granier"),
                   plot(df_site$Result[[2]], type = "Export")+labs(title="Sperry"), 
                   plot(df_site$Result[[3]], type = "Export")+labs(title="Sureau"),
                   nrow=3)
```

## Evaluation results

<!-- Stand-level evapotranspiration -->
```{r, echo=FALSE, results='asis', warning = FALSE, message=FALSE}
eval_ETR <- "ETR" %in% names(df_site$SiteData[[1]]$measuredData)
 if(eval_ETR) {
   res <- knitr::knit_child(file.path(this_path,'_ETR_Evaluation_child.Rmd'), quiet = TRUE)
   cat(res, sep = '\n')
 }
```

<!-- Stand-level sensible heat turbulent flux -->
```{r, echo=FALSE, results='asis', warning = FALSE, message=FALSE}
eval_H <- "H" %in% names(df_site$SiteData[[1]]$measuredData)
 if(eval_H) {
   res <- knitr::knit_child(file.path(this_path,'_H_Evaluation_child.Rmd'), quiet = TRUE)
   cat(res, sep = '\n')
 }
```

<!-- Stand-level latent heat turbulent flux -->
```{r, echo=FALSE, results='asis', warning = FALSE, message=FALSE}
eval_LE <- "LE" %in% names(df_site$SiteData[[1]]$measuredData)
 if(eval_LE) {
   res <- knitr::knit_child(file.path(this_path,'_LE_Evaluation_child.Rmd'), quiet = TRUE)
   cat(res, sep = '\n')
 }
```


<!-- Stand-level GPP -->
```{r, echo=FALSE, results='asis', warning = FALSE, message=FALSE}
eval_GPP <- "GPP" %in% names(df_site$SiteData[[1]]$measuredData)
 if(eval_GPP) {
   res <- knitr::knit_child(file.path(this_path,'_GPP_Evaluation_child.Rmd'), quiet = TRUE)
   cat(res, sep = '\n')
 }
```

<!-- Soil water content -->
```{r, echo=FALSE, results='asis', warning = FALSE, message=FALSE}
swc_opts <- paste0("SWC", c("", paste0(".", 1:10)))
for(soil_layer_type in swc_opts) {
   eval_SWC <- soil_layer_type %in% names(df_site$SiteData[[1]]$measuredData)
   if(eval_SWC) {
     res <- knitr::knit_child(file.path(this_path,'_SWC_Evaluation_child.Rmd'), quiet = TRUE)
     cat(res, sep = '\n')
   }
}
```

<!-- Plant transpiration -->
```{r, echo=FALSE, results='asis', warning = FALSE, message=FALSE}
eval_Eplant <- any(startsWith(names(df_site$SiteData[[1]]$measuredData),"E_"))
 if(eval_Eplant) {
   res <- knitr::knit_child(file.path(this_path,'_Eplant_Evaluation_child.Rmd'), quiet = TRUE)
   cat(res, sep = '\n')
 }
```

<!-- Leaf water potential -->
```{r, echo=FALSE, results='asis', warning = FALSE, message=FALSE}
eval_WP <- FALSE
cohNames <- row.names(df_site$InputObject[[1]]$cohorts)
for(j in 1:length(cohNames)) {
  if(paste0("MD_", cohNames[j]) %in% names(df_site$SiteData[[1]]$measuredData)) eval_WP <- TRUE
  if(paste0("PD_", cohNames[j]) %in% names(df_site$SiteData[[1]]$measuredData)) eval_WP <- TRUE
}
if(eval_WP) {
  res <- knitr::knit_child(file.path(this_path,'_LeafWP_Evaluation_child.Rmd'), quiet = TRUE)
  cat(res, sep = '\n')
}
```

