# (PART) Advanced water balance modelling {-}

# Advanced water balance model

## Design principles

The model performs soil water balance and energy balance for the input forest stand and for the period corresponding to input weather data. Soil water balance is calculated on a daily step basis for the input forest stand and for the period corresponding to input weather data. The model considers only the vertical spatial dimension of the stand, and not the horizontal distribution of plants within it. Still, the stand is divided into groups of plants (here referred to as `plant cohorts') of different species, height and leaf area index ($LAI$). As hydrological processes, the model includes water interception loss [@Gash1995], plant transpiration and hydraulic redistribution, evaporation from soil [@Ritchie1972] and the partition between infiltration and runoff [@Boughton1989]. Water exceeding soil water holding capacity is lost via deep drainage. For plant transpiration, the model determines subdaily regulation of leaf water conductance and actual transpiration involving detailed calculations of hydraulics and photosynthesis (Sperry et al. 2016). This level of complexity allows a precise estimation of photosynthesis and hydraulic redistribution of water among soil layers.


Radiation and energy balances are conducted subdaily at two levels: canopy/soil and leaf. One one hand the model keeps track of temperature variation of the air in the canopy (i.e. canopy energy balance) and in the soil (i.e. soil energy balance) as the result of energy exchanges between them and with the atmosphere. These energy balance equations are very similar to those of Best et al. (2011) for model JULES.  On the other, the model performs the energy balance at the leaf level to determine transpiration (Sperry et al. 2016). At this scale, radiation inputs include shortwave radiation from the atmosphere absorbed by the leaf and absorbed longwave radiation coming from both the atmosphere and the canopy itself. Leaf temperature is determined assuming that the temperature of the air is that of the canopy. After performing stomatal regulation, the model upscales the transpiration flux at the canopy level and the corresponding latent heat is used to complete the calculation of the energy balance at the canopy level. Note that the latent heat fluxes from evaporation from the soil and of intercepted water are not currently included in the energy balance.

## State variables

The model has the following state variables:
+ Cumulative growth degree days, $GDD$, are tracked by the model and determine leaf phenological status of winter deciduous species.
+ Daily soil moisture content dynamics on each layer $s$ are tracked using $W = \theta(\Psi_s)/ \theta_{fc,s}$, the **proportion of volumetric soil moisture in relation to field capacity**, where field capacity, $\theta_{fc,s}$, is assumed to correspond to $\Psi_{fc} = -0.033$ MPa. Soils are not allowed to contain more water than dictated by their field capacity.
+ The temperature of the canopy and of each soil layer ($T_c$ and $T_s$; both in ºC) are tracked for every subdaily step.
+ If irreversible cavitation is activated, the model also tracks $P_{embolized,i}$, the maximum value of daily drought stress so far experienced.

## Water and energy balances

### Water balance
Daily variations in soil water content (mm) can be summarized as:

\begin{equation}
\Delta{SWC} = Pr + Sm - In - Ru - Dd - Es -Tr
\end{equation}

where $Pr$ is precipitation as rainfall, $Sm$ is water from melting the snow pack (if considered), $In$ is the interception loss (i.e., water evaporated after being intercepted by the canopy), $Ru$ is surface runoff, $Dd$ is deep drainage (i.e. water percolated to layers beyond soil depth), $Es$ is evaporation from soil and $Tr$ is plant transpiration. If snow dynamics are considered, the water balance of the snow pack is defined as:

\begin{equation}
\Delta{S_{snow}} = Ps - Sm
\end{equation}

where $Ps$ is precipitation as snowfall and $Sm$ is snow melt.

### Energy balance
The canopy absorbs shortwave radiation from the atmosphere ($K_{abs,ca}$). It also absorbs longwave counterradiation from the atmosphere ($L_{abs,ca}$) and longwave radiation emmited from the soil ($L_{abs,cs}$). These inputs are counterbalanced by the longwave radiation emmited by the canopy ($L_{em,c}$) in both cases. Other energy fluxes considered are convective exchanges between the canopy and atmosphere ($H_{ca}$) and between the canopy and the soil ($H_{cs}$). Finally, energy is released to the atmosphere through latent heat ($LE_{c}$) produced via transpiration (so far, interception and soil evaporation are not included). The instantaneous energy balance equation for the canopy is thus:
\begin{equation}
  C_{c} \cdot \frac{\delta T_{c}}{\delta t} = K_{abs,ca} + (L_{abs,ca} - L_{em,c}) + (L_{abs,cs} - L_{em,c}) - LE_{c} - H_{ca} - H_{cs} 
\end{equation}
where $C_{c}$ is the canopy thermal capacitance. Like the canopy, the soil absorbs short- and longwave radiation from the atmosphere ($K_{abs,sa}$ and $L_{abs,sa}$). It also absorbs longwave radiation released by the canopy ($L_{abs,sc} = L_{em,c}$) and emmits longwave radiation ($L_{em,s}$). Note that $L_{abs,cs} \leq L_{em,s}$ because part of the radiation emmitted by the soil is sent to the atmosphere without being intercepted by the canopy. Finally, it also exchanges convective energy with the canopy ($H_{cs}$). The energy balance equation for the soil is:
\begin{equation}
  C_{s} \cdot \frac{\delta T_{s}}{\delta t} = K_{abs,sa} + L_{abs,sa} - L_{em,s} + L_{abs,sc} + H_{cs} 
\end{equation}
where $C_{s}$ is the soil thermal capacitance.

## Process scheduling

Every day the model performs the following actions: 

  * Update leaf area values according to the phenology of species.
  * Increase soil moisture due to precipitation after accounting for canopy interception loss, surface runoff and deep drainage.
  * Determine subdaily temperature and direct/diffuse irradiance variations.
  * Determine short- and longwave radiation absorved by the canopy and the soil at subdaily steps.
  * Determine plant transpiration, photosynthesis and close soil/canopy energy balance at subdaily steps. This involves the following sub-actions:
    + Determine longwave radiation emmited by soil and canopy, according to their temperature.
    + Update the water supply function of each plant cohort, according to the hydraulic model and the current soil water potential.
    + Calculate leaf temperature and photosynthesis, for shade and sunlit leaves of each plant cohort, corresponding to each transpiration value of the supply function.
    + Determine stomatal conductance, transpiration and photosynthesis on shade and sunlit leaves of each plant cohort according to a profit maximization strategy.
    + Update soil moisture after scaling transpiration from leaf to canopy level.
    + Complete energy balance of the canopy and the soil (after translating plant transpiration to latent heat and calculating convective heat exchange for both the canopy and the soil). 
  * Determine drought stress index for each plant cohort.
  * Decrease water content due to bare soil evaporation, closing the water balance.

## Model input
### Metereological input
Weather input data must include variables calculated at the **daily** scale.

+ $T_{min}$ [`MinTemperature`]: Minimum temperature (in $^{\circ} \mathrm{C}$).
+ $T_{max}$ [`MaxTemperature`]: Maximum temperature (in $^{\circ} \mathrm{C}$).
+ $RH_{min}$ [`MinRelativeHumidity`]: Minimum relative humidity (in percent).
+ $RH_{max}$ [`MaxRelativeHumidity`]: Maximum relative humidity (in percent).
+ $P$ [`Precipitation`]: Precipitation (in L·m$^{-2}$ = mm of water).
+ $Rad$ [`Radiation`]: Solar radiation after accounting for clouds (in MJ·m$^{-2}$).
+ $u$ [`WindSpeed`]: Wind speed (in m·s$^{-1}$).

We recommend meteorological input to be generated using package **meteoland** [@DeCaceres2018].


### Control parameters
Control parameters are a list of parameter values, initialized using function `defaultControl()`, that the user can modify to change the general behavior of the model. The control values relevant for the advanced water balance model are:

+ `verbose [=TRUE]`: Whether extra console output is desired during simulations.
+ `soilFunctions [= "SX"]`: Water retention curve model, either "SX" (for Saxton) or "VG" (for Van Genuchten).
+ `snowpack [= TRUE]`:  Whether dynamics of snow pack are included.
+ `drainage [= TRUE]`:  Whether water exceeding the field capacity of the bottom layer is lost by deep drainage into a non-reachable compartment.
+ `transpirationMode [= "Granier"]`: Transpiration model, in this case should be "Sperry".
+ `defaultWindSpeed [= 5]`: Default value for wind speed (in $m \cdot s^{-1}$) when this is missing (only used for leaf fall).
+ `hydraulicCostFunction [= 1]`: Variant of the hydraulic cost function used in the stomatal regulation model of Sperry & Love (2016). Values accepted are 1 (original cost function based on the derivative of supply function), 2 (leaf vulnerability curve).
+ `ndailysteps [=24]`: Number of daily substeps.
+ `thermalCapacityLAI [= 1000000]`: Canopy thermal capacitance per LAI unit.
+ `verticalLayerSize [= 100]`: The size of vertical layers (in cm) for photosynthesis calculation.
+ `cavitationRefill [= TRUE]`: If `FALSE` the model operates in a irreversible cavitation mode.
+ `taper [= TRUE]`: Whether taper of xylem conduits is accounted for when calculating aboveground stem conductance from xylem conductivity.
+ `averageFracRhizosphereResistance [= 0.15]`: Fraction to total continuum (stem+root+rhizosphere) resistance that corresponds to rhizosphere (averaged across soil water potential values).
+ `numericParams`: A list with params for numerical approximation routines.
+ `Catm [=386]`: Atmospheric CO2 concentration (in micromol $CO_2 \cdot mol^{-1}$ = ppm).


### Species parameters
Vegetation functional attributes are normally filled for each cohort by function \texttt{spwbInput()} from species identity. However, different parameters can be specified for different cohort of the same species if desired. Basic functional parameters relate to light extinction, water interception and leaf phenology:

+ $k_{PAR,i}$ [`k`]: PAR extinction coefficient.
+ $s_{water, i}$ [`g`]: Crown water storage capacity (i.e. depth of
water that can be retained by leaves and branches) per LAI unit (in $mmH_2O·LAI^{-1}$).
+ $S_{GDD,i}$ [`Sgdd`]: Growth degree days corresponding to leave
budburst (in degrees Celsius).

A second set of plant functional parameters are related to plant transpiration and photosynthesis:

+ $g_{wmin,i}$ [`Gwmin`]: Minimum leaf water conductance (in $mol·s^{-1}·m^{-2}$).
+ $g_{wmax,i}$ [`Gwmax`]: Maximum leaf water conductance (in $mol·s^{-1}·m^{-2}$).
+ $k_{rhizo,i,s}$ [`VGrhizo_kmax`]: Maximum hydraulic conductance of the rhizosphere for each soil layer.
+ $k_{\max root,i,s}$ [`VCroot_kmax`]: Maximum hydraulic conductance of the root xylem for each soil layer.
+ $c_{root,i}$ and $d_{root,i}$ [`VCroot_c` and `VCroot_c`]: Parameters of the root xylem vulnerability curve.
+ $k_{\max stem,i}$ [`VCstem_kmax`]: Maximum hydraulic conductance of the stem xylem.
+ $c_{stem,i}$ and $d_{stem,i}$ [`VCstem_c` and `VCstem_c`]: Parameters of the stem xylem vulnerability curve.
+ $V298_{max,i}$ [`Vmax298`]: Maximum Rubisco carboxylation rate at 25ºC (in $\mu mol CO_2·s^{-1}·m^{-2}$).
+ $J298_{max,i}$ [`Jmax298`]: Maximum rate of electron transport at 25ºC (in $\mu mol e ·s^{-1}·m^{-2}$).}
+ $P_{rootdisc,i}$ [`pRootDisc`]: Relative conductance of roots that leads to hydraulic disconnection from soil.
+ $k_{rhizo,i,s}$ [`VGrhizo_kmax`]: Maximum rhizosphere conductance values for each soil layer.
+ $k_{root,i,s}$ [`VCroot_kmax`]: Maximum root xylem conductance values for each soil layer.

## Model output
Function `spwb` with `transpirationMode = "Sperry"` returns a list object whose elements are data tables. Each table has dates as rows and has different output variables:

+ `WaterBalance`: Components of the climatic and soil daily water balance (i.e. net precipitation, infiltration, runoff, plant transpiration...).
+ `Soil`: Daily variation of soil variables  (volume, moisture relative to field capacity, water potential) for soil layers.
+ `EnergyBalance`: Components of the atmosphere-canopy-soil energy balance, including latent heat, convective heat, conduction heat and radiation exchanges.
+ `PlantLAI`: Daily leaf area index for each plant cohort.
+ `PlantTranspiration`: Daily transpiration (in mm) for each plant cohort.
+ `PlantPhotosynthesis`: Daily net photosynthesis (in g C·m-2) for each plant cohort.
+ `PlantPsi`: Daily water potential of each plant (in MPa).
+ `PlantStress`: Daily stress level suffered by each plant cohort (relative whole-plant conductance).
