getSpParamsNames<-function() {
  nms <-c("Name","IFNcodes","SpIndex",
          "Genus","Family", "Order","Group",
          "GrowthForm","LifeForm","LeafShape","LeafSize","PhenologyType",
          "Hmed","Hmax","Z50","Z95","fHDmin","fHDmax",
          "a_ash","b_ash","a_bsh","b_bsh","a_btsh","b_btsh","cr",
          "a_fbt","b_fbt","c_fbt","d_fbt",
          "a_cr","b_1cr","b_2cr","b_3cr","c_1cr","c_2cr",
          "a_cw","b_cw",
          "LeafDuration","Sgdd","Tbgdd","Ssen","Phsen","Tbsen",
          "SLA","LeafDensity","WoodDensity","FineRootDensity",     
          "conduit2sapwood","r635","pDead","Al2As",               
          "LeafWidth","SRL","RLD",
          "minFMC","maxFMC",
          "LeafPI0","LeafEPS","LeafAF","StemPI0","StemEPS","StemAF",
          "LigninPercent","ParticleDensity","SAV","HeatContent",
          "gammaSWR","alphaSWR","kPAR","g",
          "Tmax_LAI","Tmax_LAIsq","Psi_Extract","Psi_Critic","WUE",
          "pRootDisc","Gswmin","Gswmax","VCleaf_kmax","VCleaf_c","VCleaf_d",
          "Kmax_stemxylem","VCstem_c","VCstem_d",
          "Kmax_rootxylem","VCroot_c","VCroot_d",
          "Narea","Vmax298","Jmax298",
          "WoodC","RERleaf","RERsapwood","RERfineroot",
          "RGRleafmax","RGRsapwoodmax","RGRfinerootmax",
          "SeedProductionHeight","RecrTreeDBH","RecrTreeHeight","RecrShrubHeight",
          "RecrTreeDensity","RecrShrubCover","RecrZ50","RecrZ95",
          "MinTempRecr","MinMoistureRecr","MinFPARRecr" )
  return(nms)
}